{100}{}{Mysterious egg.}
{101}{}{A mysterious egg of some kind.}
{102}{}{You see: }
{103}{}{A chicken of some kind}
{104}{}{TODO A fluffy ball of craziness! - or random description}
{105}{}{TODO A, um.... pink chicken? - or random description}
{106}{}{[Exit]}
{107}{}{Thanks, goodbye.}
{108}{}{*bukaw* What do you want? *bakaw!*}
{109}{}{Guns. Lots of guns.}
{110}{}{Drugs, please!}
{111}{}{I would like more please!}
{112}{}{There you go!}
