#include "define.h"
#define NAME "CheatChicken"

#include "MrowrPurr/Debug.h"
#include "MrowrPurr/Display.h"

#include "sfall/sfall.h"
#include "sfall/lib.arrays.h"
#include "sfall/lib.strings.h"

// Is everything loaded?
variable ready = false;

#include "CheatChicken/Messages.h"
#include "CheatChicken/Player.h"
#include "CheatChicken/Configuration.h"
#include "CheatChicken/Data.h"
#include "CheatChicken/Egg.h"
#include "CheatChicken/Hooks.h"
#include "CheatChicken/Startup.h"

procedure start begin
    display_msg("START");
    display("HELLO FROM CHEAT CHICKEN");
    debug("HELLO FROM CHEAT CHICKEN DEBUG");
    if game_loaded then call startup;
end

