#
#   This file was built using Sfall Script Editor.
#
{101}{}{}                                                   # obj_dude.int    ; Player script.
{102}{}{Script Test 0}                                      # Test0.int       ; Used to Test Scripts
{103}{}{Script Test 1}                                      # Test1.int       ; Used to Test Scripts
{104}{}{Script Test 2}                                      # Test2.int       ; Used to Test Scripts
{105}{}{Script Test 3}                                      # Test3.int       ; Used to Test Scripts
{106}{}{Script Test 4}                                      # Test4.int       ; Used to Test Scripts
{107}{}{Script Test 5}                                      # Test5.int       ; Used to Test Scripts
{108}{}{Arroyo Warrior}                                     # ACWarior.int    ; Generic Warrior in Arroyo
{109}{}{Arroyo Villager}                                    # ACVillgr.int    ; Generic Villager of Arroyo
{110}{}{Mynoc}                                              # ACMynoc.int     ; Mynoc, Bridge Guard of Arroyo
{111}{}{Arroyo Elder}                                       # AHElder.int     ; Elder of Arroyo
{112}{}{Hakunin}                                            # AHHakun.int     ; Hakunin, Shaman of Arroyo
{113}{}{Door}                                               # Door.int        ; generic locked and trapped door
{114}{}{Generic}                                            # Generic.int     ; Generic dialog for scripts
{115}{}{Chest}                                              # AILkBox.int     ; Locked box in Arroyo Elder's room
{116}{}{Lockbox}                                            # Containr.int    ; Generic locked and trapped container
{117}{}{Brahmin}                                            # ACBrahmn.int    ; Brahmin for pen in Arroyo
{118}{}{Spore Plant}                                        # ACSporPl.int    ; Spore plants in Arroyo
{119}{}{}                                                   # ZClRat.int      ; Generic lesser rat
{120}{}{Lesser Scorpion}                                    # ZClScorp.int    ; Generic lesser scorpion
{121}{}{Lesser Mantis}                                      # ZClManti.int    ; Generic lesser mantis
{122}{}{Lesser Deathclaw}                                   # ZClDthCL.int    ; Generic lesser death claw
{123}{}{Vase}                                               # AIVase.int      ; Vase in Arroyo Villager's Hut
{124}{}{Chest}                                              # AIChest.int     ; Chest in Arroyo Shaman's Hut
{125}{}{Arroyo Caves}                                       # ArCaves.int     ; Map Script for Arroyo Caves
{126}{}{Wooden Door}                                        # DoorL100.int    ; Generic Locked Door (+100%) (Wood)
{127}{}{Arroyo Village}                                     # ArVillag.int    ; Map Script for Arroyo Village
{128}{}{Arroyo Bridge}                                      # ArBridge.int    ; Map Script for Arroyo Bridge
{129}{}{Old Door}                                           # AICavDor.int    ; Locked wooden door in Arroyo Caves
{130}{}{Floor Plate}                                        # SprTrp0.int     ; Generic spear Trap (0)
{131}{}{Floor Plate}                                        # SprTrp50.int    ; Arroyo Spear Trap for Caves (50)
{132}{}{Floor Plate}                                        # SprTrp51.int    ; Arroyo Spear Trap for Caves (50)
{133}{}{Floor Plate}                                        # SprTrp52.int    ; Arroyo Spear Trap for Caves (50)
{134}{}{Floor Plate}                                        # SprTrp53.int    ; Arroyo Spear Trap for Caves (50)
{135}{}{Door}                                               # AIBkDor.int     ; Door w/out a handle In Arroyo Caves
{136}{}{Reliant}                                            # DCAddict.int    ; Addict from the den
{137}{}{Guard}                                              # dcG2Grd.int     ; Gang 2 Guard in the Den
{138}{}{Townsperson}                                        # DCCustmr.int    ; Generic Customer in the Den
{139}{}{Thug}                                               # DCThug.int      ; Thug in the Den
{140}{}{Orphan}                                             # DCOrphan.int    ; Thieving Orphan in the Den
{141}{}{Joey}                                               # DCJoey.int      ; Special thug in the Den
{142}{}{Flick}                                              # DCFlick.int     ; Kwik N Save store owner in the Den
{143}{}{Guard}                                              # DCG1Grd.int     ; Gang 1 Guard in Den
{144}{}{Petey}                                              # DCPetey.int     ; Petey, the alley addict in the Den
{145}{}{Smitty}                                             # DCSmitty.int    ; Smitty the junkyard guy in the Den
{146}{}{Metzger}                                            # dcMetzge.int    ; Metzger the Slaver in the Den
{147}{}{Slaver}                                             # DCSlaver.int    ; Regular Slaver in the Den
{148}{}{Tubby}                                              # DCTubby.int     ; Tubby the store owner in the Den
{149}{}{Anna}                                               # DCAnna.int      ; Anna the Ghost in the Den
{150}{}{Vic}                                                # DCVic.int       ; Trader Vic in the Den
{151}{}{Frankie}                                            # DCFranki.int    ; Frankie, owner of the Hole in the Den
{152}{}{Rebecca}                                            # dcRebecc.int    ; Rebecca in the Den
{153}{}{Billy}                                              # DCBilly.int     ; One-tooth Billy in the Den
{154}{}{Sheila}                                             # DCSheila.int    ; Sheila, the prostitute in the Den
{155}{}{Mom}                                                # DCMom.int       ; Mom, who run's Mom's in the Den
{156}{}{Villager}                                           # DCSlvRun.int    ; Generic People for Slave Runs
{157}{}{Slave Run}                                          # DNSlvRun.int    ; Map Script for Den Slave Runs
{158}{}{Slave Cart}                                         # DISlvCrt.int    ; Slave Cart to take the Player to Den
{159}{}{Den Business Area}                                  # DenBus1.int     ; Map Script for Den business area 1
{160}{}{Den Business Area}                                  # DenBus2.int     ; Map Script for Den business area 2
{161}{}{Den Residential Area}                               # DenRes1.int     ; Map Script for Den residential area
{162}{}{Grave}                                              # diAnnGrv.int    ; Grave of Anna the ghost in the Den
{163}{}{Grave}                                              # diDadGrv.int    ; Grave of Anna the ghost's Dad in the Den
{164}{}{Grave}                                              # diMomGrv.int    ; Grave of Anna the ghost's Mom in the Den
{165}{}{Bones}                                              # diBones.int     ; Bones of Anna the ghost in the Den
{166}{}{Diary}                                              # diDiary.int     ; Diary of Anna the ghost in the Den
{167}{}{Locket}                                             # diLocket.int    ; Locket of Anna the ghost in the Den
{168}{}{Still}                                              # diStill.int     ; Still that Maggie has in the Den
{169}{}{Grave}                                              # ziGenGrv.int    ; Generic grave script
{170}{}{Black Jack}                                         # ziBlkJck.int    ; Generic black jack table
{171}{}{Slave}                                              # zcSlave.int     ; Generic slave
{172}{}{Black Jack}                                         # dcBlkJck.int    ; Den black jack table from Maggie's place
{173}{}{Door}                                               # diChcDor.int    ; Church door from the Den
{174}{}{Whiskey Bob}                                        # KCBob.int       ; Whiskey Bob from Klamath
{175}{}{Craps}                                              # dcCraps.int     ; Maggie Craps dealer in the den
{176}{}{Aldo}                                               # KCAldo.int      ; Aldo from Klamath
{177}{}{Ardin}                                              # KCArdin.int     ; Ardin from Klamath
{178}{}{Child}                                              # KChild.int      ; Child in Klamath
{179}{}{Citizen}                                            # KCitizen.int    ; Citizen of Klamath
{180}{}{Maida}                                              # KCMaida.int     ; Maida Buckner from Klamath
{181}{}{Sajag}                                              # KCSajag.int     ; Sajag from Klamath
{182}{}{Sally}                                              # KCSally.int     ; Big Nose Sally from Klamath
{183}{}{Smiley}                                             # KCSmiley.int    ; Smiley from Klamath
{184}{}{Jenny}                                              # KCJenny.int     ; Jenny from Klamath
{185}{}{Slim}                                               # KCSlim.int      ; Slim from Klamath
{186}{}{Torr}                                               # KCTorr.int      ; Torr the Shepard from Klamath
{187}{}{Dunton}                                             # KCDunton.int    ; Dunton Brothers from Klamath
{188}{}{Citizen}                                            # VCCrtCit.int    ; Vault City Courtyard Citizen
{189}{}{Traveller}                                          # VCCrtOut.int    ; Vault City Courtyard Outsider
{190}{}{Vault City Guard}                                   # VCCrtGrd.int    ; Vault City Courtyard Guard
{191}{}{Vault City Guard}                                   # VCInGrd.int     ; Vault City Inner Guard
{192}{}{Steve}                                              # VCSteve.int     ; Steve from Vault City
{193}{}{Andrew}                                             # VCAndy.int      ; Andy the Medic in the Central Vault City
{194}{}{Vault City Guard}                                   # VCGatGrd.int    ; Vault City Main Gate Guard
{195}{}{Dr. Troy}                                           # VCDrTroy.int    ; Vault City Dr. Troy in the Vault
{196}{}{Yellow Dog}                                         # KCYellow.int    ; Yellow Dog in Klamath
{197}{}{Balthas}                                            # mcBaltha.int    ; Balthas in Modoc
{198}{}{Cornelius}                                          # mcCornel.int    ; Cornelius in Modoc
{199}{}{Davin}                                              # mcDavin.int     ; Davin in Modoc
{200}{}{Farrel}                                             # mcFarrel.int    ; Farrel in Modoc
{201}{}{Grisham}                                            # mcGrisha.int    ; Grisham in Modoc
{202}{}{Jo}                                                 # mcJo.int        ; Jo in Modoc
{203}{}{Jonny}                                              # mcJonny.int     ; Jonny in Modoc
{204}{}{Karl}                                               # mcKarl.int      ; Karl in Modoc
{205}{}{Laddie}                                             # mcLaddie.int    ; Laddie in Modoc
{206}{}{Miria}                                              # mcMiria.int     ; Miria in Modoc
{207}{}{Protector}                                          # mcProtec.int    ; Protector in Modoc
{208}{}{Rose}                                               # mcRose.int      ; Rose in Modoc
{209}{}{Vegeir}                                             # mcVegeir.int    ; Vegeir in Modoc
{210}{}{Ed}                                                 # VCEd.int        ; Ed the Brahma dealer in Vault City
{211}{}{Harry}                                              # VCHarry.int     ; Happy Harry the store keep in Vault City
{212}{}{Mrs. Smith}                                         # VCFSmith.int    ; Mrs. Smith from Vault City (Farmer)
{213}{}{Melinda}                                            # VCMelind.int    ; Town Greeter Melinda, Vault City
{214}{}{Trapper}                                            # KCTrapr.int     ; Generic Trapper in trapper town (Klamath)
{215}{}{Mr. Smith}                                          # VCMSmith.int    ; Mr. Smith from Vault City (Farmer)
{216}{}{Skeeve}                                             # VCSkeeve.int    ; Skeeve, sells fake passes to Vault City
{217}{}{Proconsul Gregory}                                  # VCGreg.int      ; Proconsul Gregory of Vault City
{218}{}{Nurse Nancy}                                        # VCNancy.int     ; Nurse PHYLLIS!!! in Vault City
{219}{}{Randal}                                             # VCRandal.int    ; Chief Admenities Officer of Vault City
{220}{}{Goo}                                                # KTGoo.int       ; Toxic Goo in the rat caves (Klamath)
{221}{}{Barkus}                                             # VCBarkus.int    ; Barkus, Vault City Service Coordinator
{222}{}{Villager}                                           # VCGenVil.int    ; Generic Villager around Vault City
{223}{}{Stark}                                              # VCStark.int     ; Vault City Sargent Stark
{224}{}{Vault Gate Guard}                                   # VCVltGrd.int    ; Guard for entrance into the Vault of VC
{225}{}{Old Joe}                                            # VCOldJoe.int    ; Crazy Old Joe (Vault City)
{226}{}{Connar}                                             # VCConnar.int    ; Connar from Vault City
{227}{}{Wallace}                                            # VCWalace.int    ; Wallace the Customs Official (Vault City)
{228}{}{Lynette}                                            # VCLynett.int    ; First Citizen Lynette of Vault City
{229}{}{McClure}                                            # VCMClure.int    ; Senior Council Member MCclure (Vault City)
{230}{}{Mutated Rat}                                        # GCBrain.int     ; Intelligent rat in Gecko
{231}{}{Festus}                                             # GCFestus.int    ; Festering ghoul in Gecko
{232}{}{Gordon}                                             # GCGordon.int    ; Ghoul with economic data in Gecko
{233}{}{Hank}                                               # GCHank.int      ; Ghoul that monitors the reactor in Gecko
{234}{}{Jeremy}                                             # GCJerem.int     ; Ghoul in charge of supply cabinet in Gecko
{235}{}{Lumpy}                                              # GCLumpy.int     ; Watches the Brahmin and helps Skeeter
{236}{}{Skeeter}                                            # GCSkeetr.int    ; Gadgeteer in Gecko
{237}{}{Zomak}                                              # GCZomak.int     ; Muscle man for the Brain
{238}{}{Wooz}                                               # GCWooz.int      ; Bar owner and Tragic player
{239}{}{Lenny}                                              # GCLenny.int     ; Stuttering ghoul that can join party
{240}{}{Ghoul Guard}                                        # GCRDesk.int     ; Reactor Desk guard
{241}{}{Ghoul Worker}                                       # GCRWorkr.int    ; Reactor worker
{242}{}{Glowing Worker}                                     # GCRGlow.int     ; Reactor glowing one
{243}{}{Ghoul Guard}                                        # GCRGuard.int    ; Reactor guard
{244}{}{Robot}                                              # GCRRobot.int    ; Reactor robot
{245}{}{Ghoul Citizen}                                      # GCFolk.int      ; Townsfolk in Gecko
{246}{}{Map Script}                                         # DepoLv1.int     ; Map script for Sierra Army Depot, Level 1
{247}{}{Map Script}                                         # DepoLvA.int     ; Map script for Sierra Army Depot Undergound
{248}{}{Map Script}                                         # DepoLvB.int     ; Map script for Sierra. Underground B
{249}{}{Security Robot}                                     # WCSecBot.int    ; Sierra Base, Security Robot (generic)
{250}{}{Repair Robot}                                       # WCRepBot.int    ; Sierra Base, Repair Robot (generic)
{251}{}{Holodisk}                                           # WIEvcDsk.int    ; Sierra Base, Evacution Holodisk
{252}{}{Holodisk}                                           # WIMedDsk.int    ; Sierra Base, Medical Log 1 Holodisk
{253}{}{Holodisk}                                           # WIExpDsk.int    ; Sierra Base, Experiment Log Holodisk
{254}{}{Terminal}                                           # WSTerm1A.int    ; Security Computer, Level 1 -- Sierra Base
{255}{}{Terminal}                                           # WSTerm1B.int    ; Security Systems, Level 1 -- Sierra Base
{256}{}{Terminal}                                           # WSTerm2A.int    ; Security Computer, Level 2 -- Sierra Base
{257}{}{Terminal}                                           # WSTerm2B.int    ; Security Systems, Level 2 -- Sierra Base
{258}{}{Terminal}                                           # WSTerm2C.int    ; Auto Repair System, Level 2 -- Sierra Base
{259}{}{Terminal}                                           # WSTerm3A.int    ; Security Computer, Level 3 -- Sierra Base
{260}{}{Terminal}                                           # WSTerm3B.int    ; Skynet Terminal, Level 3 -- Sierra Base
{261}{}{Terminal}                                           # WSTerm3C.int    ; Robobrain Activator, Level 3 -- Sierra Base
{262}{}{Terminal}                                           # WSTerm4A.int    ; Security Computer, Level 4 -- Sierra Base
{263}{}{Terminal}                                           # WSTerm4B.int    ; Organ Extractor, Level 4 -- Sierra Base
{264}{}{Terminal}                                           # WSTerm4C.int    ; BioStorage Computer, Level 4 -- Sierra Base
{265}{}{Paper}                                              # WIPaswrd.int    ; Piece of paper with the password on it
{266}{}{Private Dobbs}                                      # WCDobbs.int     ; Private Dobbs, Sierra Army Depot
{267}{}{Brain Bot}                                          # WCBrnBot.int    ; Brain Bot in the Army Depot
{268}{}{Elevator}                                           # ZSElev01.int    ; Generic Elevator
{269}{}{Elevator}                                           # ZSElev02.int    ; Generic Elevator
{270}{}{Lockbox}                                            # DITubBox.int    ; Tubby's box of inventory
{271}{}{Lockbox}                                            # DIFlkBox.int    ; Flick's box of inventory
{272}{}{Tandi}                                              # SHTandi.int     ; Tandi the talking head NCR1
{273}{}{Spear Trap}                                         # ATSrTrp0.int    ; Arroyo Spear Trap for Caves (50)
{274}{}{Spear Trap}                                         # ATSrTrp1.int    ; Arroyo Spear Trap for Caves (50)
{275}{}{Spear Trap}                                         # ATSrTrp2.int    ; Arroyo Spear Trap for Caves (50)
{276}{}{Spear Trap}                                         # ATSrTrp3.int    ; Arroyo Spear Trap for Caves (50)
{277}{}{Spear Trap}                                         # ATSrTrp4.int    ; Arroyo Spear Trap for Caves (50)
{278}{}{Spear Trap}                                         # ATSrTrp5.int    ; Arroyo Spear Trap for Caves (50)
{279}{}{Spear Trap}                                         # ATSrTrp6.int    ; Arroyo Spear Trap for Caves (50)
{280}{}{Spear Trap}                                         # ATSrTrp7.int    ; Arroyo Spear Trap for Caves (50)
{281}{}{Spear Trap}                                         # ATSrTrp8.int    ; Arroyo Spear Trap for Caves (50)
{282}{}{Spear Trap}                                         # ATSrTrp9.int    ; Arroyo Spear Trap for Caves (50)
{283}{}{Spear Trap}                                         # ATSrTrpA.int    ; Arroyo Spear Trap for Caves (50)
{284}{}{Spear Trap}                                         # ATSrTrpB.int    ; Arroyo Spear Trap for Caves (50)
{285}{}{Spear Trap}                                         # ATSrTrpC.int    ; Arroyo Spear Trap for Caves (50)
{286}{}{Spear Trap}                                         # ATSrTrpD.int    ; Arroyo Spear Trap for Caves (50)
{287}{}{Spear Trap}                                         # ATSrTrpE.int    ; Arroyo Spear Trap for Caves (50)
{288}{}{Spear Trap}                                         # ATSrTrpF.int    ; Arroyo Spear Trap for Caves (50)
{289}{}{Ghost Cave One}                                     # GSTCAV1.int     ; Modoc Ghost Cave 1
{290}{}{Ghost Cave Two}                                     # GSTCAV2.int     ; Modoc Ghost Cave 2
{291}{}{Ghost Farm}                                         # GSTFARM.int     ; Modoc Ghost Farm
{292}{}{Modoc Brahmin Field}                                # MODBRAH.int     ; Modoc Brahmin Field
{293}{}{Modoc Garden}                                       # MODGARD.int     ; Modoc Garden
{294}{}{Modoc Inn}                                          # MODINN.int      ; Modoc Inn
{295}{}{Modoc Main}                                         # MODMAIN.int     ; Modoc Main
{296}{}{Modoc Shit}                                         # MODSHIT.int     ; Modoc Under the Shitter
{297}{}{Mod Well}                                           # MODWELL.int     ; Modoc Under the Well
{298}{}{Ncr Area 2}                                         # NCR2.int        ; NCR area 2
{299}{}{Arroyo Gardens}                                     # ArGarden.int    ; Arroyo Gardens map script
{300}{}{Gecko}                                              # ACGecko.int     ; generic Gecko creature
{301}{}{Broc Flower}                                        # AIBroc.int      ; Arroyo Broc Flower
{302}{}{Xander Root}                                        # AIXander.int    ; Arroyo Xander Root
{303}{}{Brahmin}                                            # ZCBrahmn.int    ; Generic Brahmin
{304}{}{Balthas Wife}                                       # mcBalWif.int    ; Modoc Balthas wife
{305}{}{Brahmin}                                            # mcBrahmn.int    ; Modoc brahmin
{306}{}{Wild Dog}                                           # mcAtkDog.int    ; Modoc Attack Dog
{307}{}{Rocks}                                              # miDclRks.int    ; Modoc Rocks in front of the death claw cage
{308}{}{Rocks}                                              # miShtRks.int    ; Modoc Rocks under the shitter
{309}{}{Wall Safe}                                          # miWalSfe.int    ; Modoc Farrel's wall safe
{310}{}{Coin Bag}                                           # miCoinBg.int    ; Modoc Coin bags at the bottom of the well
{311}{}{Toilet}                                             # miToilet.int    ; Modoc Toliet
{312}{}{Box}                                                # miLstFnd.int    ; Modoc Lost and Found at Rose's
{313}{}{Jordan}                                             # ACJordan.int    ; Jordan. Trains player in Melee
{314}{}{Aunt Morlis}                                        # ACMorlis.int    ; Aunt Morlis. Has flint to give player
{315}{}{Lucas}                                              # ACFist.int      ; Standing Fist. Trains player in Unarmed
{316}{}{Feargus}                                            # ACEric.int      ; Whiny person asking to fix the well
{317}{}{Well}                                               # ASWell.int      ; Arroyo Well. It's broken. Fix w/ Repair
{318}{}{Gruthar}                                            # OCGrutha.int    ; Vault 13 Gurthar the Deathclaw leader
{319}{}{Map Script}                                         # Kladwtwn.int    ; Map Script for Klamath Downtown
{320}{}{Skeeter}                                            # SCSkeete.int    ; Skeeter Script for NCR entrance area
{321}{}{Nagor}                                              # ACNagor.int     ; You cousin who has lost his dog
{322}{}{Smoke}                                              # ACDog.int       ; Nagor's dog Smoke
{323}{}{Ncr Area 1}                                         # Ncr1.int        ; map script for Ncr 1
{324}{}{Ncr Area 3}                                         # Ncr3.int        ; map script for Ncr 3
{325}{}{Ncr Area 4}                                         # Ncr4.int        ; map script for Ncr 4
{326}{}{Ncr Area Entrance}                                  # Ncrent.int      ; map script for Ncr Entrance
{327}{}{Mikey}                                              # SCMikey.int     ; Mikey the Lizard Dealer in NCR entrance
{328}{}{Mikey's box}                                        # SIMbox.int      ; Mikey's inventory box, off screen
{329}{}{Emitter}                                            # WSEmit1a.int    ; Emitter, Level 1, Section A   (Sierra Base)
{330}{}{Emitter}                                            # WSEmit1b.int    ; Emitter, Level 1, Section B   (Sierra Base)
{331}{}{Emitter}                                            # WSEmit1c.int    ; Emitter, Level 1, Section C   (Sierra Base)
{332}{}{Emitter}                                            # WSEmit1d.int    ; Emitter, Level 1, Section D   (Sierra Base)
{333}{}{Emitter}                                            # WSEmit1e.int    ; Emitter, Level 1, Section E   (Sierra Base)
{334}{}{Emitter}                                            # WSEmit2a.int    ; Emitter, Level 2, Section A   (Sierra Base)
{335}{}{Emitter}                                            # WSEmit2b.int    ; Emitter, Level 2, Section B   (Sierra Base)
{336}{}{Emitter}                                            # WSEmit2c.int    ; Emitter, Level 2, Section C   (Sierra Base)
{337}{}{Emitter}                                            # WSEmit2d.int    ; Emitter, Level 2, Section D   (Sierra Base)
{338}{}{Emitter}                                            # WSEmit3a.int    ; Emitter, Level 3, Section A   (Sierra Base)
{339}{}{Emitter}                                            # WSEmit3b.int    ; Emitter, Level 3, Section B   (Sierra Base)
{340}{}{Force Field}                                        # WSFeld1a.int    ; F. Field, Level 1, Section A   (Sierra Base)
{341}{}{Force Field}                                        # WSFeld1b.int    ; F. Field, Level 1, Section B   (Sierra Base)
{342}{}{Force Field}                                        # WSFeld1c.int    ; F. Field, Level 1, Section C   (Sierra Base)
{343}{}{Force Field}                                        # WSFeld1d.int    ; F. Field, Level 1, Section D   (Sierra Base)
{344}{}{Force Field}                                        # WSFeld1e.int    ; F. Field, Level 1, Section E   (Sierra Base)
{345}{}{Force Field}                                        # WSFeld2a.int    ; F. Field, Level 2, Section A   (Sierra Base)
{346}{}{Force Field}                                        # WSFeld2b.int    ; F. Field, Level 2, Section B   (Sierra Base)
{347}{}{Force Field}                                        # WSFeld2c.int    ; F. Field, Level 2, Section C   (Sierra Base)
{348}{}{Force Field}                                        # WSFeld2d.int    ; F. Field, Level 2, Section D   (Sierra Base)
{349}{}{Force Field}                                        # WSFeld3a.int    ; F. Field, Level 3, Section A   (Sierra Base)
{350}{}{Force Field}                                        # WSFeld3b.int    ; F. Field, Level 3, Section B   (Sierra Base)
{351}{}{Klaxon}                                             # WSKlaxon.int    ; Changes lights to Flashing w/ Sierra on Alert
{352}{}{Buster}                                             # SCBuster.int    ; Buster the gun dealer at the entrance to NCR
{353}{}{Bookshelf}                                          # SIShelf1.int    ; One of Buster's inventory shelves
{354}{}{Bookshelf}                                          # SIShelf2.int    ; One of Buster's inventory shelves
{355}{}{Bookshelf}                                          # SIShelf3.int    ; One of Buster's inventory shelves
{356}{}{Raider}                                             # ECRaider.int    ; Random Encounter Raider
{357}{}{Peasant}                                            # ECPeasnt.int    ; Random Encounter Peasant
{358}{}{Merchant}                                           # ECMrchnt.int    ; Random Encounter Merchant
{359}{}{Guard}                                              # ECGuard.int     ; Random Encounter Gaurd
{360}{}{Rawhide Patron}                                     # SCRawpat.int    ; Rawhide patron in NCR Entrance
{361}{}{Floor}                                              # WTElFlr2.int    ; Electric Floor on Level 2 Sierra Base
{362}{}{Plasma Trap}                                        # WTPlTrp0.int    ; Plasma Trap for Sierra Base(-30)
{363}{}{Plasma Trap}                                        # WTPlTrp1.int    ; Plasma Trap for Sierra Base(-30)
{364}{}{Terminal}                                           # WSPwrDwn.int    ; Power Switch for the Sierra Base
{365}{}{Bulletin Board}                                     # KSBboard.int    ; Klamath bulletin Board
{366}{}{Gate}                                               # ASCrlDr.int     ; Arroyo Corral Gate
{367}{}{Goo}                                                # ATGoo.int       ; Goo in the Garden Map
{368}{}{Door}                                               # KSCVDoor.int    ; Door in Klamath Rat Caves
{369}{}{Door}                                               # KSMalldr.int    ; Door in Klamall..get key from Slim or Dog
{370}{}{}                                                   # ZCGecko.int     ; Generic gecko
{371}{}{}                                                   # ZCLGecko.int    ; Generic Golden Gecko
{372}{}{Map Script}                                         # 2ndSt.int       ; 2nd Street Map Script
{373}{}{Map Script}                                         # ChopShop.int    ; Chop Shop Map Script
{374}{}{Map Script}                                         # GeckPwpl.int    ; Gecko Power Plant Map Script
{375}{}{Map Script}                                         # GeckTunl.int    ; Gecko Tunnels Map Script
{376}{}{Map Script}                                         # KlaCnyn.int     ; Klamath Canyon Map Script
{377}{}{Map Script}                                         # MBase12.int     ; Military Base Level 1,2 Map Script
{378}{}{Map Script}                                         # MBase34.int     ; Military Base Level 3,4 Map Script
{379}{}{Map Script}                                         # MBClose.int     ; Military Base Closed Map Script
{380}{}{Map Script}                                         # ModShit.int     ; Map Script for Modoc Shitter
{381}{}{Map Script}                                         # NCR1.int        ; Map Script for NCR1
{382}{}{Map Script}                                         # NCR2.int        ; Map Script for NCR2
{383}{}{Map Script}                                         # NCR3.int        ; Map Script for NCR3
{384}{}{Map Script}                                         # NCR4.int        ; Map Script for NCR4
{385}{}{Map Script}                                         # NCREx.int       ; Map Script for NCR Exit
{386}{}{Map Script}                                         # Stable.int      ; Map Script for Stables
{387}{}{Map Script}                                         # V13_Orig.int    ; Map Script for Original Vault 13
{388}{}{Map Script}                                         # V13Ent.int      ; Map Script for Vault 13 Entrance
{389}{}{Map Script}                                         # V15_Orig.int    ; Map Script for Original Vault 15
{390}{}{Map Script}                                         # V15Ent.int      ; Map Script for Vault 15 Entrance
{391}{}{Map Script}                                         # Vault13.int     ; Map Script for Vault 13
{392}{}{Map Script}                                         # Vault15.int     ; Map Script for Vault 15
{393}{}{Map Script}                                         # VaultNec.int    ; Map Script for Necropolis Vault
{394}{}{Map Script}                                         # VCtyVlt.int     ; Map Script for Vault City Vault
{395}{}{Map Script}                                         # Virgin.int      ; Map Script for Virgin (these still exist?)
{396}{}{Still}                                              # kstill.int      ; Script for the still in Klamath
{397}{}{Bar Customer}                                       # kcggcust.int    ; Script for Klamath golden gecko customers
{398}{}{Bar Customer}                                       # kcbhcust.int    ; Script for Klamath buckner house customers
{399}{}{Vortis}                                             # SCVortis.int    ; Script for Vortis in NCR Entrance
{400}{}{Bath Attendant}                                     # kcbgirl.int     ; Script for Klamath bath girl
{401}{}{Slaves}                                             # SCSlaves.int    ; Script for the Slaves in NCR Entrance
{402}{}{Scorpion}                                           # Kcscorp.int     ; Script for Klamath scorpions on graze map
{403}{}{Brahmin}                                            # Kcbrahmn.int    ; Script for Klamath brahmin on graze map
{404}{}{Car}                                                # ZSDrvCar.int    ; Drivable Car for the player
{405}{}{Table}                                              # diVicTbl.int    ; Den, table that Vic works at
{406}{}{Map Script}                                         # Klagraz.int     ; Map Script for Klamath graze map
{407}{}{Map Script}                                         # CarDesrt.int    ; Car Out of Gas Desert Map
{408}{}{Map Script}                                         # GeckSetl.int    ; Map Script for Gecko Settlememt
{409}{}{Map Script}                                         # VCtyCtyd.int    ; Map Script for Vault City Courtyard
{410}{}{Corvega}                                            # Kscorveg.int    ; Klamath broken car with fuel injection
{411}{}{Map Script}                                         # KlaToxCv.int    ; Klamath Toxic Caves  Map Script
{412}{}{Metal Door}                                         # SISlvdor.int    ; Slave pen door for NCR Entrance
{413}{}{Map Script}                                         # RndDsrt.int     ; Random Encounter Desert Map Script
{414}{}{Map Script}                                         # RndCoast.int    ; Random Encounter Coast Map Script
{415}{}{Map Script}                                         # RndMnt.int      ; Random Encounter Mountain Map Script
{416}{}{Lockbox}                                            # Kidbox.int      ; Klamath dunton inventory box
{417}{}{Lockbox}                                            # Kibbox.int      ; Klamath buckner inventory box
{418}{}{Lockbox}                                            # Kisbox.int      ; Klamath sajag inventory box
{419}{}{Ratch}                                              # SCRatch.int     ; Ratch junk dealer in NCR Entrance
{420}{}{Boxer}                                              # ncBoxer.int     ; New Reno Generic Boxer
{421}{}{Pete McKneely}                                      # ncMcKnee.int    ; New Reno Mike McKneely
{422}{}{Evan Hollyfeld}                                     # ncHollyf.int    ; New Reno Evan Hollyfeld
{423}{}{Masticator}                                         # ncTyson.int     ; New Reno Mike Tyson
{424}{}{Scientist}                                          # ncScient.int    ; New Reno Generic Scientist
{425}{}{Merk}                                               # SCMerk.int      ; NCR guy named Merk kind of the Moffia
{426}{}{Fan}                                                # ncBoxFan.int    ; New Reno Boxing Fan
{427}{}{Drug Dealer}                                        # ncDrgDlr.int    ; New Reno Drug Dealer
{428}{}{Casino Patron}                                      # ncCasPat.int    ; New Reno Casino Patron
{429}{}{Pimp}                                               # ncPimp.int      ; New Reno Generic Pimp
{430}{}{Junkie}                                             # ncJunkie.int    ; New Reno Generic Junkie
{431}{}{Furniture}                                          # Stuff.int       ; signals critters on steal attempt by dude
{432}{}{Floor}                                              # Trespass.int    ; same as stuff only for an area
{433}{}{Ground}                                             # ATDeath.int     ; Spatial telling the player about Nagor dead
{434}{}{Holodisk}                                           # SIFakHlo.int    ; Fake vault13 holo disk you get from Merk: NCR
{435}{}{Lenny}                                              # SCLenny.int     ; Lenny in NCR Entrance area
{436}{}{Box}                                                # SIPtbox.int     ; Temporary box for the players crap.
{437}{}{Prostitute}                                         # ncProsti.int    ; New Reno Prostitute with billions of messages
{438}{}{Slave}                                              # ncSlave.int     ; New Reno Slaves
{439}{}{Rico}                                               # ncRico.int      ; New Reno Rico, Monte's thug
{440}{}{Porn Actress}                                       # ncActres.int    ; New Reno Porn Actress
{441}{}{Fluffer}                                            # ncFluffe.int    ; New Reno Porn Fluffer/Extra
{442}{}{Map Script}                                         # Klacanyn.int    ; Map Script for Klamath Canyon
{443}{}{Wolf}                                               # ECWlfPck.int    ; Military Base Wolf Pack
{444}{}{Generator}                                          # ESPwrGen.int    ; Military Base Power Generator
{445}{}{Door}                                               # ESLkDor.int     ; Military Base Locked Door (-30)
{446}{}{Super Mutant}                                       # ECGenMut.int    ; Military Base Generic Mutant
{447}{}{Salvatore's Man}                                    # ncSalMen.int    ; New Reno Salvatore's Men
{448}{}{Bishop's Man}                                       # ncBisMen.int    ; New Reno Bishop's Men
{449}{}{Mordino's Man}                                      # ncMorMen.int    ; New Reno Mordino's Men
{450}{}{Wright's Child}                                     # ncWriTee.int    ; New Reno Wright's Sons & Daughters
{451}{}{Casino Bouncer}                                     # ncCasBou.int    ; New Reno Generic Casino Bouncer
{452}{}{Mira}                                               # SCMira.int      ; Ncr Entrance bartender
{453}{}{New Reno Virgin Street}                             # NewR1.int       ; New Reno Map Virgin Street
{454}{}{New Reno 2nd Street}                                # NewR2.int       ; New Reno Map 2nd Street
{455}{}{New Reno Commercial Row}                            # NewR3.int       ; New Reno Map Commercial Row
{456}{}{New Reno East Side}                                 # NewR4.int       ; New Reno Map East Side
{457}{}{New Reno Stables}                                   # NewRSt.int      ; New Reno Map Stables
{458}{}{New Reno Chop Shop}                                 # NewRCS.int      ; New Reno Map Chop Shop
{459}{}{New Reno Gologtha}                                  # NewRGo.int      ; New Reno Map Gologtha
{460}{}{New Reno Bishop Basement}                           # NewRBa.int      ; New Reno Map Bishop Basement
{461}{}{Holodisk}                                           # EIOutDsk.int    ; Military Base Holodisk (Outside)
{462}{}{Holodisk}                                           # EILv1Dsk.int    ; Military Base Holodisk (Level 1)
{463}{}{Holodisk}                                           # EILv2Dsk.int    ; Military Base Holodisk (Level 2)
{464}{}{Holodisk}                                           # EILv3Dsk.int    ; Military Base Holodisk (Level 3)
{465}{}{Holodisk}                                           # EILv4Dsk.int    ; Military Base Holodisk (Level 4)
{466}{}{Guard}                                              # SCGteGrd.int    ; NCR Gate Guard
{467}{}{Mine Cart}                                          # ESMinCrt.int    ; Military Base Mine Cart to explode on door
{468}{}{Melchior}                                           # ECMelchr.int    ; Melchoir the Magnificent (psuedo-mage)
{469}{}{Mutated Beast}                                      # ECMutRat.int    ; Mutated Rats in Military Base
{470}{}{FEV Goo}                                            # ETGoo.int       ; FEV Goo in the Military Base
{471}{}{Guard Captain}                                      # SCGGCap.int     ; Gate Guard Captain in NCR Entrance
{472}{}{Slave Overseer}                                     # SCslvovr.int    ; Slave overseer in NCR Entrance
{473}{}{Melchior's Pet}                                     # ECMelPet.int    ; Melchior's Pets
{474}{}{Slaver Guard}                                       # SCslvgrd.int    ; Slave guards
{475}{}{Door}                                               # SIclsdor.int    ; Closing wood door
{476}{}{Terminal}                                           # SITerm.int      ; NCR Entrance terminals in the slave pen
{477}{}{Slot Machine}                                       # ziSlots.int     ; Generic Slot Machine
{478}{}{Child}                                              # ncWriChi.int    ; New Wright children
{479}{}{Sheb}                                               # ncSheb.int      ; New Reno Sheb
{480}{}{Guard}                                              # SCMrkGrd.int    ; Merk's Guards NCR Entrance
{481}{}{Emitter}                                            # SIEmtr.int      ; Emitter for the front gate NCR Entrace
{482}{}{Force Field}                                        # SIFField.int    ; Force field in NCR Entrace
{483}{}{Sulik}                                              # Kcsulik.int     ; Sulik from Klamath
{484}{}{Dr. Henry}                                          # SCHenry.int     ; Dr. Henry NCR 1
{485}{}{Guard}                                              # SCCarGrd.int    ; Carlson's guard NCR2
{486}{}{Carlson Guards Attack}                              # STCaratk.int    ; Spatial script for carlson's guards
{487}{}{Carlson's Gate Guards}                              # SCcgtgrd.int    ; Carlson's gate guard
{488}{}{Prisoner}                                           # VCOutPrs.int    ; Vault City Outsider Prisoner (Generic)
{489}{}{Prisoner}                                           # VCCitPrs.int    ; Vault City Citizen Prisoner (Generic)
{490}{}{Citizen}                                            # VCGenFam.int    ; Vault City Generic Family
{491}{}{Amenities Aid}                                      # VCAmAid.int     ; Vault City Amenities Aid
{492}{}{Desk Guard}                                         # GCRDesk.int     ; Gecko Reactor Desk Guard
{493}{}{Ghoul Worker}                                       # GCRGhoul.int    ; Gecko Reactor Ghoul Worker
{494}{}{Glowing One}                                        # GCRGlow.int     ; Gecko Glowing One
{495}{}{Ghoul Guard}                                        # GCRGuard.int    ; Gecko Red Door Guard
{496}{}{Robot}                                              # GCRobot.int     ; Gecko Reactor Robot
{497}{}{Ghoul}                                              # GCFolk.int      ; Gecko Townsfolk
{498}{}{Worshipper}                                         # GCWorshp.int    ; Gecko Worshippers
{499}{}{Harold}                                             # GCHarold.int    ; Harold in Gecko
{500}{}{Officer}                                            # GCPACOff.int    ; Gecko Powered Armor Com Officer
{501}{}{Toto}                                               # SCToto.int      ; Toto helper bot in NCR 1
{502}{}{Dorothy}                                            # SCDoroth.int    ; Dorothy Repair chick in NCR 1
{503}{}{Townsperson}                                        # ncPerson.int    ; New Reno Generic Townsperson/Citizen
{504}{}{Ghoul Guard}                                        # GCYGuard.int    ; Gecko Yellow Door Guard
{505}{}{Ghoul Guard}                                        # GCGuard.int     ; Gecko Generic Guard
{506}{}{Gond}                                               # SCGond.int      ; Ranger guard, NCR1
{507}{}{Duppo}                                              # SCDuppo.int     ; Stockman's yard owner NCR 1
{508}{}{Stuff}                                              # SIdtbl.int      ; Stockman's table
{509}{}{Bob}                                                # SCSalBob.int    ; Salt Beef bob NCR 3
{510}{}{Casino Girl}                                        # ziDceGrl.int    ; Generic Casino Girl with Dice Game
{511}{}{Casino Girl}                                        # niDceGrl.int    ; New Reno Casino Girl with Dice Game
{512}{}{Magic Eight Ball}                                   # zi8Ball.int     ; EPA Magic 8 Ball
{513}{}{Brahmin}                                            # ncAngBra.int    ; New Reno Angry Brahmin
{514}{}{Slot Machine}                                       # niMcGSlt.int    ; New Reno McGee's Slot Machine
{515}{}{Old Man McGee}                                      # ncMcGee.int     ; New Reno Old Man (Bobby) McGee
{516}{}{Three Card Monte}                                   # nc3Monte.int    ; New Reno Three Card Monte
{517}{}{Algernon}                                           # ncAlgern.int    ; New Reno Algernon
{518}{}{Bill}                                               # ncBill.int      ; New Reno Bill (Trees Lounge)
{519}{}{Bodyguard}                                          # ncBisGrd.int    ; New Reno Bishop's Bodyguards
{520}{}{John Bishop}                                        # ncBishop.int    ; New Reno John Bishop
{521}{}{Casino Machine}                                     # niCasMac.int    ; New Reno Casino Machine
{522}{}{Chop Shop Boy}                                      # ncChpBoy.int    ; New Reno Chop Shop Boys
{523}{}{Chris Wright}                                       # ncChrWri.int    ; New Reno Chris Wright
{524}{}{Cody}                                               # ncCody.int      ; New Reno Cody
{525}{}{Corsican Bother}                                    # ncCorBro.int    ; New Reno Corsican Bothers
{526}{}{Eldridge}                                           # ncEldrid.int    ; New Reno Eldridge
{527}{}{Ethyl Wright}                                       # ncEthWri.int    ; New Reno Ethyl Wright
{528}{}{Father Tully}                                       # ncFTully.int    ; New Reno Father Tully
{529}{}{HumperdumperDIDO}                                   # ncHumper.int    ; New Reno HumperdumperDIDO
{530}{}{Lil' Jesus Mordino}                                 # ncLilJes.int    ; New Reno Lil' Jesus Mordino
{531}{}{Jagged Jimmy J}                                     # ncJimmyJ.int    ; New Reno Jagged Jimmy J
{532}{}{Keith Wright}                                       # ncKeiWri.int    ; New Reno Keith Wright
{533}{}{Lee Anne Bishop}                                    # ncLABish.int    ; New Reno Lee Anne Bishop
{534}{}{Pretty Boy Lloyd}                                   # ncLloyd.int     ; New Reno Pretty Boy Lloyd
{535}{}{Mason}                                              # ncMason.int     ; New Reno Mason
{536}{}{Guard}                                              # ncMyrGrd.int    ; New Reno Myron's Guards
{537}{}{Myron}                                              # nhMyron.int     ; New Reno Myron (Talking Head)
{538}{}{Nikki}                                              # ncNikki.int     ; New Reno Darlin' Nikki
{539}{}{Orville Wright}                                     # ncOrvill.int    ; New Reno Orville Wright
{540}{}{Pit Boss}                                           # ncPitBos.int    ; New Reno Generic Pit Boss
{541}{}{Renesco the Rocket-Man}                             # ncRenesc.int    ; New Reno Renesco the Rocket-Man
{542}{}{Researcher}                                         # ncResear.int    ; New Reno Stables Researcher
{543}{}{Boss Salvatore}                                     # ncSalvat.int    ; New Reno Boss Salvatore
{544}{}{Stuart Little}                                      # ncStuLit.int    ; New Reno Stuart Little (Agent)
{545}{}{T-Ray}                                              # ncTRay.int      ; New Reno T-Ray
{546}{}{Bitch}                                              # ncBitch.int     ; New Reno Corsican Brothers Bitches
{547}{}{Wright Child}                                       # ncWriPly.int    ; New Reno Wright Children Playing
{548}{}{NCR Police}                                         # SCCop.int       ; NCR police officer
{549}{}{Oswald}                                             # SCOswald.int    ; NCR 1 captive in cell
{550}{}{Dusty}                                              # SCDusty.int     ; NCR 1 bartender Dusty
{551}{}{Jules}                                              # ncJules.int     ; New Reno Jules
{552}{}{Miss Kitty}                                         # ncKitty.int     ; New Reno Miss Kitty
{553}{}{Bartender}                                          # ncBarten.int    ; New Reno Bartender
{554}{}{Deputy Karl}                                        # SCKarl.int      ; Karl NCR Deputy
{555}{}{Cell Door}                                          # SIKdoor.int     ; Karl's guard door
{556}{}{Big Jesus Mordino}                                  # ncBigJes.int    ; New Reno Big Jesus Mordino
{557}{}{Hoss}                                               # SCHoss.int      ; Hoss, bully in NCR 1 map
{558}{}{Mutagenic Serum}                                    # SImserum.int    ; Mutagen Serium you get from the crazy doctor
{559}{}{Box}                                                # niSalBox.int    ; New Reno Salvatore Bartender Shop Inventory
{560}{}{Box}                                                # niMorBox.int    ; New Reno Mordino Bartender Shop Inventory
{561}{}{Box}                                                # niBisBox.int    ; New Reno Bishop Bartender Shop Inventory
{562}{}{Box}                                                # niTmpBox.int    ; New Reno Personal Inventory Swap Box
{563}{}{Doctor Jubilee}                                     # SCDocJub.int    ; Doctor Jubilee NCR Map1
{564}{}{Door}                                               # GSYDoor.int     ; Yellow Door in Gecko Reactor
{565}{}{Door}                                               # GSRDoor.int     ; Red Door in Gecko Reactor
{566}{}{Bookcase}                                           # SIdshelf.int    ; Doctors shelf in NCR 1
{567}{}{Sheriff Dumont}                                     # SCsherif.int    ; Sheriff of NCR on Map 1
{568}{}{Elise}                                              # SCElise.int     ; Rangers leader chick
{569}{}{Ranch Hand}                                         # SCwrhand.int    ; Westin Ranch Hands
{570}{}{Felix}                                              # SCFelix.int     ; Felix Westin's forman
{571}{}{Westin}                                             # SCWestin.int    ; Westin big dude in NCR on NCR 3
{572}{}{Rondo}                                              # SCRondo.int     ; Rondo Ranger NCR 1
{573}{}{Robodog}                                            # SCRobo.int      ; Robodog NCR 1
{574}{}{Stairs}                                             # niBisSta.int    ; New Reno Bishop's stairs
{575}{}{Hal}                                                # SCHal.int       ; Hal Drive Leader
{576}{}{Gunther}                                            # SCGunthr.int    ; Gunther Tandi's assistant, NCR 2
{577}{}{Brahmin}                                            # ECCrtBra.int    ; Random Encounter Brahmin for carts
{578}{}{Caravan Master}                                     # ECCvnMst.int    ; Random Encounter Caravan Master
{579}{}{Caravan Driver}                                     # ECCvnDrv.int    ; Random Encounter Caravan Driver
{580}{}{Caravan Guard}                                      # ECCvnGrd.int    ; Random Encounter Caravan Guard
{581}{}{Raider}                                             # ECRadLdr.int    ; Random Encounter Raider Leader
{582}{}{Mobster}                                            # ECMobstr.int    ; Random Encounter Mobster (Outside New Reno)
{583}{}{Hunter}                                             # ECHntLdr.int    ; Random Encoutner Hunting Party Leader
{584}{}{Hunter}                                             # ECHunter.int    ; Random Encounter Hunting Party
{585}{}{Ranger}                                             # ECRanger.int    ; Random Encounter NCR Rangers (Patrol)
{586}{}{Mercenary}                                          # ECMercs.int     ; Random Encounter Mercenaries
{587}{}{Mercenary}                                          # ECMrcLdr.int    ; Random Encounter Mercenary Leader
{588}{}{Raider}                                             # ECRadGrp.int    ; Random Encounter Raider Party
{589}{}{Caravan Driver}                                     # ECRndDrv.int    ; Random Encounter Other Caravan Driver
{590}{}{Caravan Guard}                                      # ECRndGrd.int    ; Random Encounter Other Caravan Guard
{591}{}{Patrol Guard}                                       # ECVltPat.int    ; Random Encounter Vault City Patrols
{592}{}{Patrol Captain}                                     # ECVltCpt.int    ; Random Encounter Vault City Patrol Capt.
{593}{}{Farmer}                                             # ECFarmer.int    ; Random Encounter Farmer
{594}{}{Brahmin}                                            # ECBraHrd.int    ; Random Encounter Brahmin Herd
{595}{}{Brahmin}                                            # ECLedBra.int    ; Random Encounter Lead Brahmin
{596}{}{Traveler}                                           # ECTrvlr.int     ; Random Encounter Traveler
{597}{}{Patrol Guard}                                       # ECGhlPat.int    ; Random Encounter Ghoul Patrol
{598}{}{Patrol Captain}                                     # ECGhlCpt.int    ; Random Encounter Ghoul Patrol Capt.
{599}{}{Patrol Guard}                                       # ECMutPat.int    ; Random Encounter Mutant Patrol
{600}{}{Patrol Captain}                                     # ECMutCpt.int    ; Random Encounter Mutant Patrol Capt.
{601}{}{Brahmin Driver}                                     # ECBraDrv.int    ; Random Encounter Brahmin Driver
{602}{}{Rustler}                                            # ECBraRst.int    ; Random Encounter Brahmin Rustler
{603}{}{Squatter}                                           # ECSquatr.int    ; Random Encounter Squatters
{604}{}{Abolitionist}                                       # ECAbolst.int    ; Random Encounter Abolitionist
{605}{}{Bootlegger}                                         # ECMonShn.int    ; Random Encounter Moonshine Runner
{606}{}{Super Mutant}                                       # ECRogMut.int    ; Random Encounter Rogue Super Mutants
{607}{}{Fisherman}                                          # ECFshrmn.int    ; Random Encounter Fisherman
{608}{}{Slaver}                                             # ECSlaver.int    ; Random Encounter Slaver
{609}{}{Trapper}                                            # ECTrappr.int    ; Random Encounter Trapper
{610}{}{Carlson's Kid}                                      # SCCarkid.int    ; Carlson's kid
{611}{}{Carlson}                                            # SCCarlsn.int    ; Carlson
{612}{}{}                                                   # Animfrvr.int    ; Animate forever
{613}{}{Officer Jack}                                       # SCofjack.int    ; Officer Jack NCR 1
{614}{}{The Enlightened One}                                # SCEnlOne.int    ; Enlightend One NCR 1
{615}{}{Door}                                               # diDoor.int      ; Den Auto Closing Door
{616}{}{Computer}                                           # GsTerm.int      ; Gecko robot control terminal
{617}{}{Brahmn}                                             # SCBrahmn.int    ; NCR Map 4 Brahmin yeah.
{618}{}{Deathclaw}                                          # SCdthcla.int    ; NCR Map 4 Death Claw's
{619}{}{Exit Grid}                                          # SIExit.int      ; NCR Map 4 exit grid control
{620}{}{Computer}                                           # SSComp.int      ; NCR Map 1 the computer that blows up
{621}{}{Feargus}                                            # SCFergus.int    ; NCR Map 2 Fergus... Receptionist
{622}{}{Ariel}                                              # OCAriel.int     ; Vault13 Ariel character
{623}{}{Fannie Mae}                                         # RCFannie.int    ; Fannie Mae the hooker in Redding
{624}{}{Computer Terminal}                                  # OSComptr.int    ; Computer in Vault 13
{625}{}{Dalia}                                              # OCDalia.int     ; Dalia in Vault 13
{626}{}{Dar}                                                # OCDar.int       ; Dar Deathclaw guard in Vault 13
{627}{}{Dave}                                               # OCDave.int      ; Dave NPC in Vault 13
{628}{}{Gordon}                                             # OCGordon.int    ; Gordon the shrine dude
{629}{}{Out of Business Sign}                               # ziClosed.int    ; Generic "Out of Business" signs
{630}{}{Reactor Control Machinery}                          # gsReactr.int    ; Script to animate Reactor
{631}{}{Jimmy}                                              # OCJimmy.int     ; Jimmy dude in computer room Vault 13
{632}{}{Joseph}                                             # OCJoseph.int    ; Doctor in Vault13
{633}{}{Matt}                                               # OCMatt.int      ; Matt prisonner in Vault13
{634}{}{}                                                   # RCFitRat.int    ; Redding Fighting Molerats
{635}{}{Map Script}                                         # RedMEnt.int     ; Redding Mine Entrance Map Script
{636}{}{V13 map script}                                     # vault13.int     ; Vault13 map
{637}{}{Sandy}                                              # OCSandy.int     ; Sandy child in Vault 13
{638}{}{Box}                                                # ziTmpBox.int    ; Generic Temporary swap box
{639}{}{Thearn}                                             # OCThearn.int    ; Thearn Vault 13 Guard
{640}{}{Box}                                                # miGriBox.int    ; Modoc Grisham Merchant box
{641}{}{Box}                                                # miJoBox.int     ; Modoc Jo Merchant box
{642}{}{Valdis}                                             # OCValdis.int    ; Valdis Death claw guard on lvl 3 Vault 13
{643}{}{Computer Terminal}                                  # OSVdrcmp.int    ; Vault 13 entrance map door control
{644}{}{Metal Locker}                                       # OILocker.int    ; Lockers in Vault 13
{645}{}{Footlocker}                                         # OIftlkr.int     ; Footlockers in Vault 13
{646}{}{Deathclaw Guard}                                    # OCGrunt.int     ; Generic Deathclaw guard in Vault 13
{647}{}{Goris}                                              # OCGoris.int     ; Goris possible NPC deathclaw
{648}{}{Box}                                                # miBalBox.int    ; Modoc Balthas Merchant box
{649}{}{Metal Locker}                                       # SILocker.int    ; Guard's lockers in NCR 1
{650}{}{Cheater}                                            # Cheater.int     ; Cheater Character
{651}{}{V15 map Script}                                     # vault15.int     ; Vault 15 map
{652}{}{Phil}                                               # bcPhil.int      ; Phil secret guard guy in Vault 15
{653}{}{Bill}                                               # bcBill.int      ; Bill fluff guy in Vault 15
{654}{}{Butcher}                                            # mcButchr.int    ; Slaughter house guys in Modoc
{655}{}{Dalia}                                              # bcDalia.int     ; Guard who guards a trail
{656}{}{John}                                               # BCJohn.int      ; John Vault 15 guy
{657}{}{Jones}                                              # BCJones.int     ; Jones Vault 15 doctor
{658}{}{Karla}                                              # BCKarla.int     ; Karla Guard for vault 15 secrect entrance
{659}{}{V15 Secrect entrance map}                           # V15Sent.int     ; vault 15 secrect entrance map
{660}{}{Rebecca}                                            # BCRebecc.int    ; Vault 15 Entrance Rebecca
{661}{}{Door}                                               # miDoor.int      ; Modoc Doors
{662}{}{Death Claw}                                         # mcDthClw.int    ; Modoc Rose's "Chicken"
{663}{}{Roberta}                                            # BCRobert.int    ; Roberta in Vault13 entrance
{664}{}{Sara}                                               # BCSara.int      ; Sara vault15 entrance
{665}{}{Zeke}                                               # BCZeke.int      ; Zeke Vault15 entrance mayor dude
{666}{}{Brahmin}                                            # BCBrahmn.int    ; Brahmn in Vault 15 Entrance
{667}{}{Wood Door}                                          # BIEntDr.int     ; Entrance door traped
{668}{}{Chrissy}                                            # BCCrissy.int    ; Crissy Rebecca's daughter
{669}{}{Darion}                                             # BCDarion.int    ; Darion the big bad dude in Vault15
{670}{}{Darion's Guard}                                     # BCDargrd.int    ; Darion's guards Vault 15
{671}{}{Darion's Dog}                                       # BCDardog.int    ; Darion's dog Vault 15
{672}{}{Cassidy}                                            # VCCasidy.int    ; Casidy the  bar person in Vault City
{673}{}{Well}                                               # miWell.int      ; Modoc Well
{674}{}{Mole Rat}                                           # mcMolRat.int    ; Modoc Shitter Mole Rat
{675}{}{Brahmin Chunk}                                      # miBraMea.int    ; Modoc Brahmin Chunks
{676}{}{Brahmin}                                            # mcKilBra.int    ; Modoc Slaughterhouse brahmin
{677}{}{Elevator Door}                                      # BSelev.int      ; Door to secret elevator
{678}{}{Dog}                                                # mcKilDog.int    ; Dog that hangs out at the slaughter house
{679}{}{Rat}                                                # mcRat.int       ; Modoc Garden Rat
{680}{}{Sun Spot}                                           # ziSunSpt.int    ; Generic Sun Spot
{681}{}{Bess}                                               # mcBess.int      ; Modoc Bess the Brahmin
{682}{}{Box}                                                # miJkyBox.int    ; Modoc Jerky box
{683}{}{Craps Dealer}                                       # ZCCrpdel.int    ; Craps dealer. talk to him and play craps
{684}{}{Vault 15 Guard}                                     # BCGenGrd.int    ; Generic Vault 15 Khan Guard
{685}{}{Slag}                                               # mcSlag.int      ; Modoc Generic Slag
{686}{}{Rug}                                                # mtRug.int       ; Modoc Spacial Script for Rug
{687}{}{Child}                                              # mcChild.int     ; Modoc Child
{688}{}{Aileen}                                             # hcAileen.int    ; Aileen in Broken Hills
{689}{}{Guard}                                              # hcBnkGrd.int    ; Bank Guard in Broken Hills
{690}{}{Doc Holiday}                                        # hcDoc.int       ; Doc in Broken Hills
{691}{}{Henchman}                                           # hcencha.int     ; Henchman A in Broken Hills
{692}{}{Henchman}                                           # hcenchb.int     ; Henchman B in Broken Hills
{693}{}{Woman}                                              # hcfemale.int    ; Female in Broken Hills
{694}{}{Francis}                                            # hcFranci.int    ; Francis in Broken Hills
{695}{}{Frank}                                              # hcFrank.int     ; Frank in Broken Hills
{696}{}{Ghoul}                                              # hcGhoul.int     ; Ghoul in Broken Hills
{697}{}{Liz}                                                # hcLiz.int       ; Liz in Broken Hills
{698}{}{Man}                                                # hcmale.int      ; Male in Broken Hills
{699}{}{Manson}                                             # hcManson.int    ; Manson in Broken Hills
{700}{}{Marcus}                                             # hcMarcus.int    ; Marcus in Broken Hills
{701}{}{Miner}                                              # hcMiners.int    ; Miners in Broken Hills
{702}{}{Mutant}                                             # hcMutant.int    ; Mutant in Broken Hills
{703}{}{Bill}                                               # hcOutfit.int    ; Outfitter in Broken Hills
{704}{}{Phil}                                               # hcPhil.int      ; Phil the bartender in Broken Hills
{705}{}{Steve}                                              # hcSteve.int     ; Steve in Broken Hills
{706}{}{Supervisor}                                         # hcSuper.int     ; Supervisor in Broken Hills
{707}{}{Zaius}                                              # hcZaius.int     ; Zaius in Broken Hills
{708}{}{Jacob}                                              # hcJacob.int     ; Jacob in Broken Hills
{709}{}{Chemistry Set}                                      # hchems.int      ; Chemistry Set in Broken Hills
{710}{}{Prop}                                               # miGstPrp.int    ; Modoc Ghost Farm Prop
{711}{}{Door}                                               # BSSdor1.int     ; Shack doors on V15SENT map
{712}{}{Computer}                                           # BSComp1.int     ; Library computer Vault15
{713}{}{Chad}                                               # hcchad.int      ; Chad from Broken Hills
{714}{}{Spore Plant}                                        # ECPlant.int     ; Random Encounter Spore Plant
{715}{}{Gecko}                                              # ECGecko.int     ; Random Encounter Gecko
{716}{}{Radscorpion}                                        # ECScorp.int     ; Random Encounter Scorpions
{717}{}{}                                                   # ECRat.int       ; Random Encounter Rats
{718}{}{Warrior}                                            # ECWarPty.int    ; Random Encounter War Party
{719}{}{Cannibal}                                           # ECCanibl.int    ; Random Encounter Cannibals
{720}{}{Outcast}                                            # ECOutCst.int    ; Random Encounter Outcasts
{721}{}{Holy Person}                                        # ECHlyPpl.int    ; Random Encounter Holy People
{722}{}{Nomad}                                              # ECNomad.int     ; Random Encounter Nomads
{723}{}{Homeless Person}                                    # ECHomles.int    ; Random Encounter Homeless
{724}{}{Bandit}                                             # ECBandit.int    ; Random Encounter Bandit
{725}{}{Robber}                                             # ECRobber.int    ; Random Encounter Robber
{726}{}{Highwayman}                                         # ECHiwymn.int    ; Random Encounter Highwaymen
{727}{}{Slaver}                                             # ECSlvRun.int    ; Random Encounter Slavers on a Slave Run
{728}{}{Slave}                                              # ECSlave.int     ; Random Encounter Slaves
{729}{}{Partier}                                            # ECRavPty.int    ; Random Encounter Rave Party
{730}{}{Mantis}                                             # ECMantis.int    ; Random Encounter Mantis
{731}{}{Brahmin}                                            # ECBrahmn.int    ; Random Encounter Brahmin
{732}{}{Dog}                                                # ECWldDog.int    ; Random Encounter Wild Dogs
{733}{}{Computer}                                           # BSComp2.int     ; Darion's computer Vault 15
{734}{}{Computer}                                           # BSComp3.int     ; Force Field computer Vault 15
{735}{}{Computer Terminal}                                  # BSComp4.int     ; Force Field computer Vault 15 near entrance
{736}{}{Computer}                                           # BSComp5.int     ; Computer terminal 5 in Vault 15
{737}{}{Power Generator}                                    # BSPower.int     ; Power Generator in Vault 15
{738}{}{Force Field}                                        # BSField.int     ; Force field in Vault 15
{739}{}{Peasant}                                            # mcPeasan.int    ; Modoc Peasant Person
{740}{}{Emitter}                                            # BSEmtr.int      ; Vault 15 Emitter
{741}{}{Vault Door}                                         # OSV13dr.int     ; Vault 13 Door
{742}{}{Security Door}                                      # OSDoor1.int     ; Vault 13 Door that shows the deathclaws
{743}{}{Bess Encounter}                                     # rndBess.int     ; Random Encounter for Bess outside of modoc
{744}{}{Bess}                                               # ECBess.int      ; Bess in Bess's Encounter (she's dead jim)
{745}{}{Brahmin}                                            # ECBesCow.int    ; One of the Brahmin in Bess's herd
{746}{}{Angela Bishop}                                      # ncAngBis.int    ; New Reno Angela Bishop
{747}{}{Tommy "The Balls"}                                  # ncTommy.int     ; New Reno Tommy the Balls (YEAH! OUR HERO)
{748}{}{Safe}                                               # niABisSf.int    ; New Reno Angela Bishop's Safe
{749}{}{Safe}                                               # niMrBSf.int     ; New Reno Mr. Bishop's Safe
{750}{}{Safe}                                               # niMrsBSf.int    ; New Reno Mrs. Bishop's Safe
{751}{}{Safe}                                               # niOWriSf.int    ; New Reno Orville Wright's Safe
{752}{}{Grave}                                              # niPriGrv.int    ; New Reno Pritchard's Grave
{753}{}{Dresser}                                            # niWridrs.int    ; New Reno Richard Wright's Dresser
{754}{}{Grave}                                              # niWriGrv.int    ; New Reno Righard Wright's Grave
{755}{}{Still}                                              # niWriSti.int    ; New Reno Wright Stills
{756}{}{Ramirez}                                            # ncRamire.int    ; New Reno Ramirez
{757}{}{Cave 1 Random Encounter Map}                        # cave01.int      ; Cave1 Random Encounter map
{758}{}{Box}                                                # niRenBox.int    ; New Reno Renesco Box
{759}{}{Door}                                               # niDoor.int      ; New Reno Door
{760}{}{Cave 2 Random Encounter Map}                        # cave02.int      ; Cave 2 Random Encounter map
{761}{}{Cave 3 Random Encounter Map}                        # cave03.int      ; Cave 3 Random Encounter map
{762}{}{Cave 4 Random Encounter Map}                        # cave04.int      ; Cave 4 Random Encounter map
{763}{}{Cave 2 Random Encounter Map}                        # cave05.int      ; Cave 5 Random Encounter map
{764}{}{Door}                                               # VIEntDor.int    ; Vault City Entrance Door
{765}{}{Map Script}                                         # VCtyDwtn.int    ; Vault City Downtown Map script
{766}{}{Trap Door}                                          # miTrpDor.int    ; Modoc Ghost Farm Trap Door
{767}{}{Lockbox}                                            # Hilbox.int      ; Broken Hills Liz inventory box
{768}{}{Room}                                               # ntLydRom.int    ; New Reno Lloyd Room
{769}{}{Thomas Moore}                                       # VCMoore.int     ; Thomas Moore from Vault City
{770}{}{Door}                                               # ZILckDor.int    ; Generic Locked Door (-20)
{771}{}{Locker}                                             # niLydBox.int    ; New Reno Lloyd's Loot Box
{772}{}{Manhole}                                            # niManhol.int    ; New Reno Manhole to Lloyd's Loot
{773}{}{Grave}                                              # niLydGrv.int    ; New Reno Lloyd's Loot Grave
{774}{}{Supply Guard}                                       # VCSupGrd.int    ; Vault City Supply Guard Martin
{775}{}{Map Script}                                         # broken1.int     ; Map Script for Broken Hills Map 1
{776}{}{Map Script}                                         # Rndexcow.int    ; Map Script for Low Luck cow bomb encounter
{777}{}{Mad Brahmin}                                        # ECCowBmb.int    ; The cows that blow...
{778}{}{Hakeswill}                                          # RCHakes.int     ; Hakeswill from Redding
{779}{}{Redding Downtown}                                   # REDDown.int     ; Redding Downtown map script
{780}{}{Map Script}                                         # BHRndDst.int    ; Broken Hills Caravan Desert Map
{781}{}{Map Script}                                         # BHRndMtn.int    ; Broken Hills Caravan Mountain Map
{782}{}{Lou}                                                # RCLou.int       ; Lou from Redding
{783}{}{Arthur}                                             # ECArthur.int    ; Arthur Leader of the special encounter knights
{784}{}{Robin}                                              # ECRobin.int     ; Robin one of the knights with Arthur
{785}{}{Bedemir}                                            # ECBedemi.int    ; Bedemir one of the knights with Arthur
{786}{}{Sir Launcelot}                                      # ECSirLau.int    ; Sir Launcelot on of the knights with Arthur
{787}{}{Galahad}                                            # ECGalaha.int    ; Galahad one of the knights with Arthur
{788}{}{Ben Wade}                                           # RCWade.int      ; Ben Wade from Radding
{789}{}{Athabaska Dick}                                     # RCDick.int      ; Athabaska Dick from Redding
{790}{}{Widow Rooney}                                       # RCRooney.int    ; Widow Rooney from Redding
{791}{}{Townsperson}                                        # RCGenPes.int    ; Generic Townsperson in Redding
{792}{}{Stanwell}                                           # RCStanwl.int    ; Stannwell from Redding
{793}{}{Savinelli}                                          # RCSavine.int    ; Savinelli from Redding
{794}{}{Marge}                                              # RCMarge.int     ; Marge LeBarge from Redding
{795}{}{Madam Modjeska}                                     # RCModjes.int    ; Madam Modjeska from Redding
{796}{}{James Hoffy}                                        # RCHoffy.int     ; James Hoffy, Caravan Master for Redding
{797}{}{Map Script}                                         # Rndholy1.int    ; Random Encoutner Holy 1 map
{798}{}{Patsy}                                              # ECPatsy.int     ; Patsy Arthur's horse Holy 1 map
{799}{}{Concorde}                                           # ECConcor.int    ; Concord Launcelot horse Holy 1 map
{800}{}{Eric}                                               # ECEric.int      ; Eric Robin's horse
{801}{}{John}                                               # ECJohn.int      ; John Bedemir's horse
{802}{}{Joshua}                                             # ECJoshua.int    ; Joshua Robin's minstrel
{803}{}{Ladder}                                             # miLadder.int    ; Modoc Shitter Ladder
{804}{}{Big Head}                                           # ECBHead.int     ; Big head special encounter
{805}{}{Black Hero}                                         # ECBlkHro.int    ; Black Hero model
{806}{}{Red Heroine}                                        # ECRedHro.int    ; Red Heroine Model
{807}{}{Set}                                                # ECSet.int       ; Set in cafe
{808}{}{Tandi}                                              # ECTandi.int     ; Tandi in Cafe
{809}{}{White Hero}                                         # ECWhro1.int     ; White Hero Model 1
{810}{}{White Hero}                                         # ECWhro2.int     ; White Hero Model 2
{811}{}{White Heroine}                                      # ECWHeon1.int    ; White Heroine Model 1
{812}{}{Box}                                                # NiJulBox.int    ; New Reno Jules Shop Inventory Box
{813}{}{Box}                                                # niEldBox.int    ; New Reno Eldridge Shop Box
{814}{}{Box}                                                # niEldBx2.int    ; New Reno Eldridge Shop Box (For Made Men)
{815}{}{Map Script}                                         # RndHoly2.int    ; Map script for Holy Knights 2
{816}{}{Vorpal Rat}                                         # ECVorRat.int    ; Vorpal Rat for Holy Knights 2
{817}{}{Dog}                                                # ECpdog.int      ; Paraih dog he joins your party.
{818}{}{Drill Seargant}                                     # Ccdrill.int     ; Drill Seargant in Colusa/Nevarro
{819}{}{Guard}                                              # Ccguard.int     ; Guard in Colusa/Nevarro
{820}{}{Technician}                                         # Cctech.int      ; Technician in Colusa/Nevarro
{821}{}{Commander}                                          # Ccmandr.int     ; Commander in Colusa Nevarro
{822}{}{Chris}                                              # CcChris.int     ; Chris the gas station attendant in Colusa
{823}{}{Quarter Master}                                     # Ccmaster.int    ; Quarter Master in Colusa/Nevarro
{824}{}{Guard}                                              # Ccgguard.int    ; Gate Guard in Colusa/Nevarro
{825}{}{Grave}                                              # ntLydGrv.int    ; New Reno Lloyd's Loot Grave (Spacial Script)
{826}{}{Car}                                                # ntCar1.int      ; New Reno Stolen Car Seed Spacial 1
{827}{}{Car}                                                # ntCar2.int      ; New Reno Stolen Car Seed Spacial 2
{828}{}{Grave}                                              # niMorGrv.int    ; New Reno Mordino Stash Grave
{829}{}{Robed Figure}                                       # ECBridge.int    ; Bridge guy Special encounter
{830}{}{Cattle Buyer}                                       # SCDrvPay.int    ; The buyer for the NCR cattle drive in redding
{831}{}{Map Script}                                         # RndBridg.int    ; Random Bridge encounter
{832}{}{Mysterious Stranger}                                # ECMstStr.int    ; Mysterious Stranger
{833}{}{Mad Brahmn}                                         # ECGCwBmb.int    ; Generic Cow bomb the bridge dude uses
{834}{}{}                                                   # ECYakuza.int    ; Random Encounter Yakuza
{835}{}{}                                                   # ECWilder.int    ; Random Encounter
{836}{}{Dog}                                                # ncWriDog.int    ; New Reno Wright Dog
{837}{}{Box}                                                # niRamBox.int    ; New Reno Box to be delivered to Ramirez
{838}{}{}                                                   # ECUniPat.int    ; Random Unity Patrol
{839}{}{}                                                   # ECTravlr.int    ; Random Travler encounter
{840}{}{Smoke}                                              # KtSmoke.int     ; displays message about smoke smell in Duntons
{841}{}{Trader}                                             # ECTrader.int    ; Random Encounter Trader
{842}{}{Scavenger}                                          # ECScaven.int    ; Random Encounter Scavengers
{843}{}{Merchant}                                           # FCMercha.int    ; San Francisco Merchants
{844}{}{Peasant}                                            # FCBadPea.int    ; San Francisco Bad Peasants
{845}{}{Arroyo Temple}                                      # ARTemple.int    ; Arroyo Temple map script
{846}{}{Dock Worker}                                        # FCDokWrk.int    ; San Franscisco Dock Worker
{847}{}{Peasant}                                            # FCGudPea.int    ; San Franscisco Good Peasant
{848}{}{Shi Guard}                                          # FCShiGrd.int    ; San Fran Shi Guards
{849}{}{Warrior}                                            # ACTemVil.int    ; Temple challenge person
{850}{}{Door}                                               # AITemDor.int    ; Temple doors that lock at the challenge
{851}{}{Klint}                                              # ACKlint.int     ; Klint the guardian of the temple exit
{852}{}{Crops}                                              # AICrops.int     ; Crops that die after a period of time
{853}{}{Shi Lab Tech}                                       # FCSlabte.int    ; San Fran Shi Lab Techs
{854}{}{Child}                                              # FCSKids.int     ; San Fran Shi Kids
{855}{}{Ghoul}                                              # GCWander.int    ; wandering ghouls in Gecko
{856}{}{Dr Fung}                                            # FCDrFung.int    ; San Fran Doctor Fung
{857}{}{Jul}                                                # OCJul.int       ; Vault 13 Denmother Guard
{858}{}{Kerith}                                             # OCKerith.int    ; Vault 13 Den Mother
{859}{}{Chest}                                              # AITemCst.int    ; Temple Chest to hold the players things
{860}{}{Ghoul}                                              # GCRGhul.int     ; Reactor Ghoul that doesn't move
{861}{}{}                                                   # ECRaiBow.int    ; Random Encounter Gays
{862}{}{}                                                   # ECMstAmy.int    ; Random Encounter Master's Army
{863}{}{Prospector}                                         # ECProspe.int    ; Random Encounter Prospecter
{864}{}{}                                                   # ECPrsgng.int    ; Random Encounter Press Gang
{865}{}{Nomad Chief}                                        # ECNomChf.int    ; Random Encounter Nomad Chief
{866}{}{Hubologist}                                         # ECElRon.int     ; Elronologist Patrol
{867}{}{Crazy}                                              # ECCrazy.int     ; Crazies from Random Encounter
{868}{}{Claim Jumper}                                       # ECClmJmp.int    ; Random Encounter Claim Jumpers
{869}{}{Cannibal}                                           # ECCanbal.int    ; Random Encounter Cannibals
{870}{}{Nomad Shamon}                                       # ECNomSha.int    ; Random Encounter Nomad Shamon
{871}{}{Marauder}                                           # ECMaradr.int    ; Random Encounter Marauder
{872}{}{Rogue}                                              # ECRogue.int     ; Random Encounter Rogue
{873}{}{Hermit}                                             # ECHermit.int    ; Random Encuonter Hermit
{874}{}{}                                                   # ECGangs.int     ; Random Encounter Gangs
{875}{}{Caravan Master}                                     # ECMstKla.int    ; Random Encounter Klamath Caravan Master
{876}{}{Caravan Master}                                     # ECMstDen.int    ; Random Encounter Den Caravan Master
{877}{}{Caravan Master}                                     # ECMstNew.int    ; Random Encounter New Reno Caravan Master
{878}{}{Caravan Master}                                     # ECMstRed.int    ; Random Encounter Redding Caravan Master
{879}{}{Caravan Master}                                     # ECMstBro.int    ; Random Encounter Broken Hills Caravan Master
{880}{}{Caravan Master}                                     # ECMstGec.int    ; Random Encounter Gecko Caravan Master
{881}{}{Caravan Master}                                     # ECMstSan.int    ; Random Encounter San Fran Caravan Master
{882}{}{Caravan Master}                                     # ECMstNCR.int    ; Random Encounter NCR Caravan Master
{883}{}{Caravan Master}                                     # ECMstV15.int    ; Random Encounter Vault 15 Caravan Master
{884}{}{Farmer's Wife}                                      # ECFrmwfe.int    ; Random Encounter Farmer's Wife
{885}{}{Farmer's Kid}                                       # ECFrmKid.int    ; Random Encounter Farmer's Kid
{886}{}{Homesteader}                                        # ECHomest.int    ; Random Encounter Homesteader
{887}{}{Homesteader's Wife}                                 # ECHomwfe.int    ; Random Encounter Homesteader's wife
{888}{}{Homesteader's Kid}                                  # ECHomkid.int    ; Random Encounter Homesteader's kid
{889}{}{Caravan Master}                                     # ECMstVC.int     ; Random Encounter Vault City Caravan Master
{890}{}{}                                                   # ECAlien.int     ; Random Encounter Alien
{891}{}{}                                                   # ECDthclw.int    ; Random Encounter Deathclaws
{892}{}{}                                                   # ECFloatr.int    ; Random Encounter Floater
{893}{}{}                                                   # ECCentur.int    ; Random Encounter Centaurs
{894}{}{Enclave Patrolman}                                  # ECElvPat.int    ; Random Encounter Enclave Patrol
{895}{}{Merc Captain}                                       # icMrcCpt.int    ; Raiders Merc Captain
{896}{}{Merc Raider}                                        # icMerc.int      ; Raiders Merc
{897}{}{"Shadow-Who-Walks"}                                 # icScout.int     ; Raiders Scout
{898}{}{Safe}                                               # iiSafe.int      ; Raiders Safe
{899}{}{}                                                   # raiders1.int    ; Raiders 1 Enterance
{900}{}{}                                                   # raiders2.int    ; Raiders 2 Caves
{901}{}{}                                                   # Hscelldr.int    ; Broken Hills bank/jail door
{902}{}{Box}                                                # niTRyBox.int    ; New Reno Chop Shop T-Ray Box
{903}{}{President Richardson}                               # qhPrzRch.int    ; Enclave President of USA
{904}{}{Howitzer}                                           # WIHowitz.int    ; Howitzer in the Sierra Base
{905}{}{Door}                                               # WIEntDor.int    ; Entrance to Sierra Base Door
{906}{}{Baby Deathclaw}                                     # OCBabDth.int    ; Vault 13 Baby deathclaws
{907}{}{Dangerous Dan}                                      # RCMcGrew.int    ; Dangerous Dan McGrew from redding
{908}{}{Doc Johnson}                                        # RCDrJohn.int    ; Painless Doc Johnson (breaks Jet)
{909}{}{Sheriff Marion}                                     # RCMarion.int    ; Sheriff Earl Marion
{910}{}{Mayor Ascorti}                                      # RCAscort.int    ; Mayor Ascorti of Redding
{911}{}{Nording}                                            # RCNord.int      ; Nording, the payoff man for Stanwell
{912}{}{Velani}                                             # RCVelani.int    ; Velani, the payoff man for Savinelli
{913}{}{Ferndown}                                           # RCFern.int      ; Ferndown, the payoff man for Wade
{914}{}{The Dragon}                                         # FCDragon.int    ; The Dragon, San Fran
{915}{}{Stable Boy}                                         # mcSblBoy.int    ; Modoc Stable Boy
{916}{}{Trader}                                             # mcTrader.int    ; Modoc Trader
{917}{}{Townsperson}                                        # mcPerson.int    ; Modoc Townspeople
{918}{}{Slag}                                               # mcSlgExt.int    ; Ghost Farm Slag Exit Guard
{919}{}{Slag}                                               # mcSlgGrd.int    ; Ghost Farm Slag Enterance Guard
{920}{}{Lo Pan}                                             # FCLopan.int     ; LoPan in SanFran... hey that Rhyms
{921}{}{Badger}                                             # FCBadger.int    ; Badger Punk in San Fran
{922}{}{Josh}                                               # RCJosh.int      ; Josh Laurance of Redding
{923}{}{Caminetto}                                          # RCCamint.int    ; Caminetto in bar fight in redding
{924}{}{Bette}                                              # RCBette.int     ; Blasphemous Bette in bar fight in redding
{925}{}{Gun Merchant}                                       # FCGunMer.int    ; Gun Merchant in San Fran
{926}{}{Door}                                               # ZIWodDor.int    ; Generic Wooden Door
{927}{}{Door}                                               # ZIMtlDor.int    ; Generic Metal Door
{928}{}{Emitter}                                            # SSEmtn2.int     ; Emitter in NCR area 2
{929}{}{Rat God}                                            # KCRatGod.int    ; Rat God in Klamath
{930}{}{}                                                   # ECBox.int       ; Random encounter box that has stuff in it
{931}{}{Kaga}                                               # ECKaga1.int     ; Random encounter Kaga 1
{932}{}{Kaga}                                               # ECKaga2.int     ; Random encounter Kaga 2
{933}{}{Kaga}                                               # ECKaga3.int     ; Random encounter Kaga 3
{934}{}{Kaga}                                               # ECKaga4.int     ; Random encounter Kaga 4
{935}{}{Kaga}                                               # ECKaga5.int     ; Random encounter Kaga 5
{936}{}{Bounty Hunter}                                      # ECBHuntr.int    ; Random Encounter Bounty Hunter
{937}{}{Computer}                                           # VIMedCom.int    ; Vault City Medical Computer
{938}{}{Computer}                                           # VICenCom.int    ; Vault City Central Computer
{939}{}{Computer}                                           # VIAloCom.int    ; Vault City Allocation Computer
{940}{}{Darrow}                                             # VCDarrow.int    ; Vault City Sub-Amenities Officer Darrow
{941}{}{Farrell}                                            # VCFarrel.int    ; Vault City Sub-Amenities Officer Farrell
{942}{}{Bar Patron}                                         # VCBarPat.int    ; Vault City Bar Patron
{943}{}{Vault Citizen}                                      # VCWrkCit.int    ; Vault City Working Citizen
{944}{}{Vault Servant}                                      # VCSlave.int     ; Vault City Slave
{945}{}{Ventilation Shaft}                                  # VIShft2b.int    ; Vault City Ventilation Shaft 2B
{946}{}{Charlie}                                            # VCCharli.int    ; Vault City Puking Charlie
{947}{}{Coolant Control Panel}                              # GSValve.int     ; Gecko Coolant Control Panel
{948}{}{Poo}                                                # ziBraPoo.int    ; Generic BRAHMIN SHIT!!! YES YES YES
{949}{}{Grant}                                              # SCWesGrd.int    ; Westin's force field guard.
{950}{}{Emitter}                                            # SSEmiWes.int    ; Westin's force field emitter.
{951}{}{Emitter}                                            # SSEmiWe1.int    ; Westin's force field on the other map.
{952}{}{Computer Terminal}                                  # SICmpWes.int    ; Westin's computer controlling the field
{953}{}{Emperor Terminal v8.8}                              # FSEmpTer.int    ; The Emperor Computer Terminal
{954}{}{Vice President Bird}                                # QCBird.int      ; Enclave, Vice President Bird
{955}{}{Martin}                                             # QCMartin.int    ; Enclave, Martin Frobishner, V13 spokesman
{956}{}{Ken Lee}                                            # FCKenLee.int    ; Ken Lee in San Francisco area
{957}{}{Sgt. Granite}                                       # QCGranit.int    ; Sgt. Granite of the Enclave Patrol
{958}{}{Frank Horrigan}                                     # QCFrank.int     ; Secret Service Agent Frank (End Boss)
{959}{}{Map Script}                                         # GeckJunk.int    ; Map Script for Gecko Junkyard
{960}{}{Map Script}                                         # GeckTunl.int    ; Map Script for Gecko Tunnels
{961}{}{Door}                                               # SSFrgDor.int    ; Door script for Fergus's door
{962}{}{Door}                                               # SSGunDor.int    ; Door script for Gunther's door
{963}{}{Door}                                               # SSFlxDor.int    ; Door script for Felix's door
{964}{}{Rope}                                               # SSRope.int      ; Rope.... don't want to explain
{965}{}{Emitter}                                            # SSEmient.int    ; Emitter/Force NCR Entrance
{966}{}{Dr. Curling}                                        # QCCurlng.int    ; Dr. Charles Curling, Chem Corps.
{967}{}{Bulletin Board}                                     # SSsign.int      ; Sign in NCR
{968}{}{Mole Rat}                                           # mcMolRat.int    ; Ghost Farm Mole Rat
{969}{}{President's Secretary}                              # QCPrsSec.int    ; President's personal intern (uh sectertary)
{970}{}{Tom Murray}                                         # QCMurray.int    ; Tom Murray, head of AEC
{971}{}{Sturdy Door}                                        # SSCrpDor.int    ; Craps table door
{972}{}{Townsperson}                                        # mcPeasan.int    ; Modoc Peasant, they attack the farm
{973}{}{Vault City Council Area}                            # VCtyCocl.int    ; Map Script Vault City Council Area
{974}{}{Air Purifier}                                       # HSPurify.int    ; Air Purifier for Broken Hills
{975}{}{Rocks}                                              # esEntRks.int    ; Military Base Enterance Rocks
{976}{}{Gambler}                                            # RCGamble.int    ; Redding Generic Gamblers
{977}{}{Spatial Script}                                     # HtCorpse.int    ; Spatial Script for Corpses
{978}{}{SCCheat}                                            # SCCheat.int     ; Cheat Character for NCR
{979}{}{Prisoner}                                           # QCGenPrs.int    ; Enclave Generic Prisoner
{980}{}{Citizen}                                            # QCGenCit.int    ; Enclave Generic Citizens
{981}{}{Guard}                                              # QCGenGrd.int    ; Enclave Generic Guards
{982}{}{Scientist}                                          # QCGenSci.int    ; Enclave Generic Scientist
{983}{}{Terminal}                                           # QIPzlTrm.int    ; Enclave terminal in the Puzzle Level
{984}{}{}                                                   # etEnter.int     ; Military Base Enterance Spacial Message
{985}{}{}                                                   # etBattle.int    ; Military Base Battle Area Spacial Message
{986}{}{Emitter}                                            # SSEmiEn1.int    ; Ncr emitters for ncr entrance on map 1
{987}{}{Blast Door}                                         # QIBstDr1.int    ; Blast Door for Reactor Off to remain closed
{988}{}{Blast Door}                                         # QIBstDr2.int    ; Blast Door for Reactor On to remain closed
{989}{}{Darrow's Stock}                                     # VIDarBox.int    ; Vault City Darrow Shop Inventory
{990}{}{Door}                                               # HSCrlDr.int     ; Jail cell door for Broken Hills
{991}{}{Super Duper Mutant}                                 # ecTlkMut.int    ; Military Base Conversation Mutants
{992}{}{Chemist}                                            # FCChemst.int    ; Chemist in San Fran
{993}{}{Grundel}                                            # ecGrunde.int    ; Military Base Mouse Hunter
{994}{}{Kid}                                                # ecMelKid.int    ; Some Town USA, Melchior's Kid
{995}{}{Retinal Scanner}                                    # WIRetScn.int    ; Retinal Scanner in the Sieera Base
{996}{}{Elevator Door}                                      # WIElvDor.int    ; Elevator Door in the Seirra Base
{997}{}{Cybernetic Receptical}                              # WIBrkBrn.int    ; Broken Brain Bot in the Sierra Base
{998}{}{Wall}                                               # WIScrtDr.int    ; Sierra Base Secert Door
{999}{}{Map Script}                                         # broken2.int     ; Map Script for Broken Hills Map 2
{1000}{}{Farrell's Stock}                                   # VIFarBox.int    ; Vault City Farrell Shop Inventory
{1001}{}{Harry's Stock}                                     # VIHarBox.int    ; Vault City Happy Harry Shop Stock
{1002}{}{Box}                                               # VICtyBox.int    ; Vault City Courtyard Temp Inventory Box
{1003}{}{Box}                                               # VIDwtBox.int    ; Vault City Downtown Temp Inventory Box
{1004}{}{Derek}                                             # dcDerek.int     ; Derek in the Den
{1005}{}{Tubby's Friend}                                    # dcTubFri.int    ; Tubby's Junkie Friends in the Den
{1006}{}{Gambler}                                           # dcGamble.int    ; Gamblers in the Den
{1007}{}{Slave}                                             # dcSlave.int     ; Pen Slaves in the Den
{1008}{}{Guard}                                             # dcMetRom.int    ; Metzger Room Guard in the Den
{1009}{}{Slaver}                                            # dcPenGrd.int    ; Slaver Pen Guard in the Den
{1010}{}{Lara}                                              # dcLara.int      ; Lara in the Den
{1011}{}{Tyler}                                             # dcTyler.int     ; Tyler in the Den
{1012}{}{Marc}                                              # dcMarc.int      ; Marc in the Den
{1013}{}{Bulletin Board}                                    # diBulBrd.int    ; Bulletin Board in the Den
{1014}{}{Slaver}                                            # dcVicGrd.int    ; Vic Guard in the Den
{1015}{}{Slaver}                                            # dcSlvGrt.int    ; Slaver Greeter in the Den
{1016}{}{Fred}                                              # dcFred.int      ; Fred in the Den
{1017}{}{Box}                                               # diFliBox.int    ; Flick Box in the Den
{1018}{}{Box}                                               # diMomBox.int    ; Mom Box in the Den
{1019}{}{Box}                                               # diSmiBox.int    ; Smitty Box in the Den
{1020}{}{Car Trunk}                                         # ZICrTrnk.int    ; generic script for Car Trunk
{1021}{}{Security Door}                                     # QIPzlDor.int    ; Door for the puzzle room in the Enclave
{1022}{}{Computer Terminal}                                 # FSPhySta.int    ; Physics computer station San Fran
{1023}{}{Computer Terminal}                                 # FSBioSta.int    ; Biology computer station San Fran
{1024}{}{Computer Terminal}                                 # FSCheSta.int    ; Chemistry computer station San Fran
{1025}{}{Lao Chou}                                          # FCLaoCho.int    ; Merchant in San Fran
{1026}{}{}                                                  # FIPaper.int     ; Scrap papers that combine San Fran
{1027}{}{}                                                  # CSVent.int      ; Ventilation shaft for Navarro
{1028}{}{Map Script}                                        # EncTrp.int      ; Map Script for Enclave Trap Rooms
{1029}{}{Dead Body}                                         # HtBody.int      ; Script for dead bodies in Broken Hills
{1030}{}{Exposed wires}                                     # QIWires.int     ; Wires on the ground in the trap room
{1031}{}{Box}                                               # diMetBox.int    ; Metzger Box from Slave Crap
{1032}{}{Slave}                                             # dcRunSlv.int    ; Den Slave Run Fleeing Slaves
{1033}{}{Slave}                                             # dcAtkSlv.int    ; Den Slave Run Hostile Slaves
{1034}{}{Slaver}                                            # dcRnSlvr.int    ; Den Slave Run Slavers
{1035}{}{Chip}                                              # FCChip.int      ; Chip San Fran
{1036}{}{Reactor}                                           # QIReactr.int    ; Reactor in the Enclave
{1037}{}{Reactor Computer}                                  # QIRctrCm.int    ; Reactor Computer in the Enclave
{1038}{}{Cash Tender}                                       # RCCshTnd.int    ; Redding Cash Tender in the Casino
{1039}{}{Cash Box}                                          # RICshBox.int    ; Cash Box for the Cash Tender
{1040}{}{Wanamingo}                                         # RCWanami.int    ; Wanamingo
{1041}{}{Bar Patron}                                        # dcStory1.int    ; Story Teller 1 in the Den
{1042}{}{Bar Patron}                                        # dcStory2.int    ; Story Teller 2 in the Den
{1043}{}{Jail Door}                                         # RIJalDor.int    ; Jail Door in Redding
{1044}{}{Suze}                                              # FCSuze.int      ; Suze in San Fran you can save her
{1045}{}{Captain Ron Meyers}                                # FCRonMey.int    ; Captain Ron Meyers in San Francisco
{1046}{}{Pen Door}                                          # diPenDor.int    ; Slave Pen Door in the Den
{1047}{}{Wanamingo Mine}                                    # RedWan1.int     ; Map Script for Wanamingo Mine
{1048}{}{Wanamingo Mine Entrance}                           # RedWame.int     ; Map Script for Wanamingo Mine Entrance
{1049}{}{Frog Morton}                                       # RCFrog.int      ; Frog Morton
{1050}{}{Dave H.}                                           # FCDaveh.int     ; Dave Handy in San Fran
{1051}{}{Door}                                              # diVicDor.int    ; Vic's Room Door in the Den
{1052}{}{Door}                                              # diRomDor.int    ; Metzger's Room Door in the Den
{1053}{}{Puking Charlie}                                    # VCCharly.int    ; Puking Charlie in Vault City Courtyard
{1054}{}{Painting}                                          # SIpaint.int     ; Painting in NCR marks Vault13 on the map
{1055}{}{Map Script}                                        # SFChina.int     ; San Fran China Map
{1056}{}{Bartender}                                         # VCCouBar.int    ; Vault City Council Area Bartender
{1057}{}{Box}                                               # VIBarBox.int    ; Vault City Slave Sale Inventory Dump
{1058}{}{Auto-Doc}                                          # VIAutDoc.int    ; Vault City Courtyard Auto Doc
{1059}{}{}                                                  # RIMinEnt.int    ; Entrance Back to the Mines
{1060}{}{Mining Tunnel}                                     # RedMTun.int     ; Map Script for Mining Tunnel
{1061}{}{Robot}                                             # KCRob.int       ; Robot on Klamath Canyon
{1062}{}{}                                                  # FIGunTbl.int    ; Gun Merchant Table San Fran
{1063}{}{Map Script}                                        # KlaMall.int     ; Map Script for Klamath Mall area
{1064}{}{Map Script}                                        # KlaTrap.int     ; Map Script for Klamath Still area
{1065}{}{Lydia}                                             # VCDwnBar.int    ; Vault City Downtown Bartender
{1066}{}{}                                                  # RedDTun.int     ; Redding Downtown Tunnels
{1067}{}{Rocketman}                                         # FCRocMan.int    ; Rocketman in San Fran
{1068}{}{AHS-7}                                             # FCOz7.int       ; Oz7 in San Fran
{1069}{}{Crockett}                                          # FCCrocke.int    ; Crockett in San Fran
{1070}{}{Amanda}                                            # VCAmanda.int    ; Vault City Coutryard Amanda, Joshua's Wife
{1071}{}{Joshua}                                            # VCJoshua.int    ; Vault City Courtyard Joshua, Slave
{1072}{}{Valerie}                                           # VCMainWk.int    ; Valerie, Vic's Daughter and Maintence Worker
{1073}{}{Teaching System}                                   # VITeach.int     ; Vault City Teaching System
{1074}{}{Crate}                                             # diCrate.int     ; Den Crate in Church
{1075}{}{Peeing Guy}                                        # VCUrine.int     ; Peeing Guy in Vault City Council Area
{1076}{}{Curtis}                                            # VCCurtis.int    ; Curtis, Amanda and Joshua's Son
{1077}{}{Marc}                                              # FCMarc.int      ; Marc, a San Fran punks
{1078}{}{Computer}                                          # FSElComp.int    ; Elronologists computer
{1079}{}{AHS-9}                                             # FCOz9.int       ; Oz9 San Fran main Elronologist dude
{1080}{}{Guard}                                             # FCElGrd.int     ; Elronologists Guards
{1081}{}{Pile of rocks}                                     # VIRocks.int     ; Pile of Rocks w/ Hidden Wrench
{1082}{}{Door}                                              # VIVltDor.int    ; Vault City 2nd floor doors
{1083}{}{Guard}                                             # dcRebGrd.int    ; Den Rebecca Guard
{1084}{}{Guard}                                             # dcRebDor.int    ; Den Rebecca Door Guard
{1085}{}{Door}                                              # diRebDor.int    ; Den Rebecca Door
{1086}{}{Wanted Sign}                                       # ZSWsign.int     ; Generic Wanted Sign
{1087}{}{Dr. Wong}                                          # FCDrwong.int    ; Dr Wong, he has Chip's spleen
{1088}{}{Table}                                             # FIlaotbl.int    ; Lao Cho's stock tables in san Fran
{1089}{}{Door}                                              # WILv1Dor.int    ; Locked Door on Level 1 Entrance
{1090}{}{Punk}                                              # FCFemPnk.int    ; San Fran Female punk
{1091}{}{Punk}                                              # FCMalPnk.int    ; San Fran Male punk
{1092}{}{Ryan}                                              # FCRyan.int      ; San Fran Rayan
{1093}{}{Box}                                               # HIBh1Box.int    ; Broken Hills Temp Inventory Box
{1094}{}{}                                                  # FCJuaVki.int    ; Juan and Vikki in San Fran
{1095}{}{Manhole}                                           # HIManHol.int    ; Manhole to Basement in Liz's Store
{1096}{}{Map Script}                                        # SFElronb.int    ; Elron Base map Script
{1097}{}{Ladder}                                            # HILadder.int    ; Ladder up to Liz's Store
{1098}{}{Punching Bag}                                      # WIPnchBg.int    ; Punching Bag in the Sierra Depot
{1099}{}{Door}                                              # WIBayDor.int    ; Sierra Base Repair Bay Door
{1100}{}{Alarm}                                             # GSAlarm.int     ; Gecko Reactor Alarm
{1101}{}{Floor Plate}                                       # WTPlTrp2.int    ; Plasma Floor Trap Level 2 of Seirra  (Left)
{1102}{}{Floor Plate}                                       # WTPlTrp3.int    ; Plasma Floor Trap Level 2 of Seirra  (Left)
{1103}{}{Floor Plate}                                       # WTPlTrp4.int    ; Plasma Floor Trap Level 2 of Seirra  (Left)
{1104}{}{Floor Plate}                                       # WTPlTrp5.int    ; Plasma Floor Trap Level 2 of Seirra  (Left)
{1105}{}{Floor Plate}                                       # WTPlTrp6.int    ; Plasma Floor Trap Level 2 of Seirra  (Left)
{1106}{}{Floor Plate}                                       # WTPlTrp7.int    ; Plasma Floor Trap Level 2 of Seirra  (Left)
{1107}{}{Floor Plate}                                       # WTPlTrp8.int    ; Plasma Floor Trap Level 2 of Seirra  (Left)
{1108}{}{Floor Plate}                                       # WTPlTrp9.int    ; Plasma Floor Trap Level 2 of Seirra  (Right)
{1109}{}{Floor Plate}                                       # WTPlTrpA.int    ; Plasma Floor Trap Level 2 of Seirra  (Right)
{1110}{}{Floor Plate}                                       # WTPlTrpB.int    ; Plasma Floor Trap Level 2 of Seirra  (Right)
{1111}{}{Floor Plate}                                       # WTPlTrpC.int    ; Plasma Floor Trap Level 2 of Seirra  (Right)
{1112}{}{Floor Plate}                                       # WTPlTrpD.int    ; Plasma Floor Trap Level 2 of Seirra  (Right)
{1113}{}{Floor Plate}                                       # WTPlTrpE.int    ; Plasma Floor Trap Level 2 of Seirra  (Right)
{1114}{}{Floor Plate}                                       # WTPlTrpF.int    ; Plasma Floor Trap Level 2 of Seirra  (Right)
{1115}{}{Emitter}                                           # WSEmit4a.int    ; Emitter, Level 4 in Sierra Base
{1116}{}{Emitter}                                           # WSEmit4b.int    ; Emitter, Level 4 in Sierra Base
{1117}{}{Emitter}                                           # WSEmit4c.int    ; Emitter, Level 4 in Sierra Base
{1118}{}{Force Field}                                       # WSFeld4a.int    ; Force Field, Level 4 in Sierra Base
{1119}{}{Force Field}                                       # WSFeld4b.int    ; Force Field, Level 4 in Sierra Base
{1120}{}{Force Field}                                       # WSFeld4c.int    ; Force Field, Level 4 in Sierra Base
{1121}{}{Hubologist}                                        # FCElrind.int    ; Elron Indoctrinee (Peasant)
{1122}{}{Computer}                                          # FSTnkCmp.int    ; Posiden Tanker computer
{1123}{}{Bunker Door}                                       # WIBnkDor.int    ; Bunker Door for the Sierra Depot
{1124}{}{Gate}                                              # miGate.int      ; Modoc Gate
{1125}{}{Box}                                               # WITrpBx1.int    ; Sierra Base Trapped Box
{1126}{}{Morton Brother}                                    # RCMorBrs.int    ; Morton Brothers, Inc.
{1127}{}{Emitter}                                           # FSEmt1.int      ; Emitter For Field 1 in San Fran
{1128}{}{Emitter}                                           # FSEmt2.int      ; Emitter For Field 2 in San Fran
{1129}{}{Emitter}                                           # FSEmt3.int      ; Emitter For Field 3 in San Fran
{1130}{}{Map Script}                                        # Cave6.int       ; Fake Vault 13 map
{1131}{}{Chet}                                              # VCChet.int      ; Illicit Allocations Officer Chet
{1132}{}{Map Script}                                        # NewRVB.int      ; New Reno Helicopter Script Map
{1133}{}{Vertibird}                                         # nsVertib.int    ; New Reno Helicopter Script Vertibird
{1134}{}{Salvatore Guard}                                   # ncHSSal1.int    ; New Reno Helicopter Script Salvatore 1
{1135}{}{Salvatore Guard}                                   # ncHSSal2.int    ; New Reno Helicopter Script Salvatroe 2
{1136}{}{Soldiers}                                          # ncHSPow1.int    ; New Reno Helicopter Script Power Armor 1
{1137}{}{Soldiers}                                          # ncHSPow2.int    ; New Reno Helicopter Script Power Armor 2
{1138}{}{Crate}                                             # niHSCrat.int    ; New Reno Helicopter Script Crate
{1139}{}{Mr. Handy}                                         # ncHSHand.int    ; New Reno Helicopter Script Handy
{1140}{}{Salvatore Guard}                                   # ncHSGSal.int    ; New Reno Helicopter Script Salvatore Guard
{1141}{}{Spacial Script}                                    # ntHSGrd.int     ; New Reno Helicopter Script Guarding Spacial
{1142}{}{Door}                                              # niEldDor.int    ; New Reno Elderidge Door
{1143}{}{Door}                                              # niSalDor.int    ; New Reno Salvatore Door
{1144}{}{Door}                                              # niMyrDor.int    ; New Reno Myron Door
{1145}{}{}                                                  # FCMonst.int     ; Monsters in PMS Tanker
{1146}{}{Map Script}                                        # SFTanker.int    ; San Fran Tanker map Script
{1147}{}{Slave}                                             # VCSlav2.int     ; Vault City Prisoner Slaves
{1148}{}{Vault Citizen}                                     # VCBarCit.int    ; Vault City Bar Patrons
{1149}{}{Door}                                              # niBasDor.int    ; New Reno Locking Doors
{1150}{}{Boxer}                                             # ncFightr.int    ; New Reno Boxer Actually Fighting
{1151}{}{Vault Door}                                        # RIVltDor.int    ; Locked Vault Door in Redding
{1152}{}{Xarn}                                              # CcXarn.int      ; Xarn in Navarro
{1153}{}{Raul}                                              # CcRaul.int      ; Raul in Navarro
{1154}{}{Quincy}                                            # CcQuincy.int    ; Quincy in Navarro
{1155}{}{Quartermaster}                                     # CcQmstr.int     ; Quartermaster in Navarro
{1156}{}{Guard}                                             # CcMedGrd.int    ; Med Lab Guard in Navarro
{1157}{}{Cybernetic Dog}                                    # CcK9.int        ; K9 in Navarro
{1158}{}{Doctor}                                            # CcDoctor.int    ; Dr Shreber in Navarro
{1159}{}{Technician}                                        # CcATech.int     ; Air Tech in Navarro
{1160}{}{Technician}                                        # CcACon.int      ; Air Control in Navarro
{1161}{}{Guard}                                             # CcDrGrd.int     ; Door Guard in Navarro
{1162}{}{Guard}                                             # Ccggbak.int     ; Gate Guard Backup in Navarro
{1163}{}{Guard}                                             # CcGrdca.int     ; Guard (combat armor) in Navarro
{1164}{}{Guard}                                             # CcGrdpa.int     ; Guard (power armor) in Navarro
{1165}{}{Technician}                                        # CcTech1.int     ; Com Tech1 in Navarro
{1166}{}{Technician}                                        # CcTech2.int     ; Com Tech2 in Navarro
{1167}{}{Technician}                                        # CcComp1.int     ; Computer Tech1 in Navarro
{1168}{}{Technician}                                        # CcComp2.int     ; Computer Tech2 in Navarro
{1169}{}{Cave In}                                           # HICaveIn.int    ; Broken Hills Caved-In mine
{1170}{}{Enclave Patroler}                                  # QCEPSqad.int    ; Enclave EP Squad (joins player in fighting
{1171}{}{Blast Door}                                        # QIEndDor.int    ; Doors at the End Fight Area
{1172}{}{Map Script}                                        # EncDet.int      ; Map Script for Enclave Detention Center
{1173}{}{Map Script}                                        # EncDock.int     ; Map Script for Enclave Dock
{1174}{}{Map Script}                                        # EncGd.int       ; Map Script for Enclave Guard Barracks
{1175}{}{Map Script}                                        # EncPres.int     ; Map Script for Enclave Presidential Area
{1176}{}{Map Script}                                        # EncRetr.int     ; Map Script for Enclave Reactor Area
{1177}{}{Map Script}                                        # EncFite.int     ; Map Script for Enclave Fight Area
{1178}{}{Security Robot}                                    # QCSecBot.int    ; Enclave Security Robot
{1179}{}{Poor Box}                                          # niTulBox.int    ; New Reno Poor Box
{1180}{}{Body}                                              # hiDead.int      ; Dead body in Broken Hills Tunnels
{1181}{}{Box}                                               # HiJacBox.int    ; Broken Hills Jacob inventory box
{1182}{}{Box}                                               # HiDocBox.int    ; Broken Hills Doc Holliday Inventory box
{1183}{}{Box}                                               # HiOutBox.int    ; Broken Hills Outfitter inventory box
{1184}{}{Caravan Guard}                                     # RCCvnGrd.int    ; Generic Caravan Guard
{1185}{}{Caravan Driver}                                    # RCCvnDrv.int    ; Generic Caravan Driver
{1186}{}{Ring Announcer}                                    # ncAnounc.int    ; New Reno Boxing Anouncer
{1187}{}{Ring Girl}                                         # ncRngGrl.int    ; New Reno Ring Grrrl
{1188}{}{Boxer}                                             # ncPrzFtr.int    ; New Reno Prize Fighter
{1189}{}{Door}                                              # VIVltDr2.int    ; Vault Doors in Vault 8
{1190}{}{Cheat Character}                                   # ncCheat.int     ; New Reno Cheat Character
{1191}{}{Holodisk}                                          # WIGNNDsk.int    ; Sierra Base GNN Transscript
{1192}{}{Holodisk}                                          # WIMisDsk.int    ; Sierra Base Mission Statement Disk
{1193}{}{Holodisk}                                          # FIElrDsk.int    ; Elronologist Holodisk
{1194}{}{Note}                                              # HINote.int      ; Script for Francis/Zaius Note
{1195}{}{Dogmeat}                                           # ECDogMet.int    ; Dog Meat Special encounter
{1196}{}{Cat's Paw Magazine #5}                             # niCatPw5.int    ; New Reno Cat's Paw magazine 5
{1197}{}{Raiders Map}                                       # niRaiMap.int    ; New Reno Raiders Map in Bishop's Safe
{1198}{}{Pariah Dog}                                        # ECPariah.int    ; Pariah Dog in Low Luck encounter
{1199}{}{Klaxon}                                            # QIKlaxon.int    ; Klaxon Lights for Enclave when under alert
{1200}{}{Mine}                                              # IIMine.int      ; Mines in Raiders Cave
{1201}{}{Pit}                                               # IIPit.int       ; Pits in the Raiders Cave
{1202}{}{Tanker Merchant}                                   # FCTnkGmr.int    ; Tanker Gun Merchant
{1203}{}{Tanker Bartender}                                  # FCTnkBar.int    ; Tanker Bartenter
{1204}{}{Tanker Merchant}                                   # FCTnkMer.int    ; Tanker Merchant
{1205}{}{}                                                  # FITguntb.int    ; Tanker Gun Merchant's Table
{1206}{}{}                                                  # FITMerTb.int    ; Tanker Merchant's Table
{1207}{}{Emitter}                                           # FSPemtr1.int    ; Palace Emitter 1
{1208}{}{Emitter}                                           # FSPemtr2.int    ; Palace Emitter 2
{1209}{}{Emitter}                                           # FSPemtr3.int    ; Palace Emitter 3
{1210}{}{Emitter}                                           # FSEmpEmt.int    ; Emporor Computer's Force Field
{1211}{}{Fallout 2 Hintbook}                                # niF2Hint.int    ; New Reno Fallout 2 Hintbook
{1212}{}{}                                                  # csTouch.int     ; Script to signal if dude touches containers
{1213}{}{}                                                  # csArea.int      ; Script to signal if dude enters an area
{1214}{}{Guard}                                             # RCAscGrd.int    ; Generic Guard for Ascorti's Bar
{1215}{}{Prospector}                                        # ECLdPros.int    ; Random Encounter Lead Prospector
{1216}{}{Bootleggers}                                       # ECLdBoot.int    ; Random Encounter Lead Bootlegger
{1217}{}{}                                                  # csOpen.int      ; Script to signal if dude uses door w/o permis
{1218}{}{Dan}                                               # hcDan.int       ; Dan, Spouse of murdered conspirator.
{1219}{}{Shitty Comedian}                                   # ncComedi.int    ; New Reno Comedian
{1220}{}{Trashcan Singer}                                   # ncBand.int      ; New Reno Trashcan Band
{1221}{}{Map Script}                                        # ARDead.int      ; Destroyed Arroyo Bridge map script
{1222}{}{}                                                  # csGate.int      ; Script to signal if dude uses gate w/o permis
{1223}{}{Grave}                                             # niWilGrv.int    ; New Reno Coffin Willie's Grave
{1224}{}{Coffin Willie}                                     # ncWillie.int    ; New Reno Coffin Willie
{1225}{}{Keyless entry computer}                            # FSFobTer.int    ; Fob Terminal in San Fran Tanker
{1226}{}{Keyless entry Door}                                # FSFobDor.int    ; Fob Door in San Fran Tanker
{1227}{}{Computer}                                          # ccNComp.int     ; Navarro Computer
{1228}{}{Kohl}                                              # vcKohl.int      ; Vault City Info Officer Kohl
{1229}{}{Child}                                             # ECChild.int     ; Random Encounter Children
{1230}{}{Cook}                                              # ccCook.int      ; Navarro Cook
{1231}{}{Turret}                                            # ccTurret.int    ; Navarro Turret
{1232}{}{Brian}                                             # hcBrian.int     ; Brian, the Power Technician
{1233}{}{Generator}                                         # hiPower.int     ; Power Generator for Broken Hills
{1234}{}{Console}                                           # hiConsol.int    ; Power Station Console in Broken Hills
{1235}{}{Giant Ant}                                         # hcAnt1.int      ; Standard Broken Hills Ant
{1236}{}{Giant Ant}                                         # hcAnt2.int      ; Broken Hills Ant/ Missing Persons Quest
{1237}{}{Door}                                              # csXDoor.int     ; Another lousy door script -sig xarn to leave
{1238}{}{}                                                  # htSecret.int    ; Spatial for secret area of Broken Hills Mine
{1239}{}{Box}                                               # niEthBox.int    ; New Reno Ethyl Wright Shop Box
{1240}{}{Eric}                                              # hcEric.int      ; Eric the Smelly Boy, Broken Hills
{1241}{}{}                                                  # htFlies.int     ; Spatial Flies script for Broken Hills
{1242}{}{Box}                                               # viRanBox.int    ; Randal's Stock Box in Vault City
{1243}{}{Giant Scorpion}                                    # iiScorp.int     ; Raiders Scorpions 2X poison
{1244}{}{Jane}                                              # RCJane.int      ; Redding Jackpot Jane
{1245}{}{}                                                  # VTAloMrk.int    ; Spatial Script for Allocation Computer VCity
{1246}{}{Map Script}                                        # Cave7.int       ; Fake Vault 13 map
{1247}{}{Dermal Pip Boy}                                    # niDermal.int    ; New Reno Dermal Pip Boy
{1248}{}{Pooch}                                             # ncEldDog.int    ; New Reno Eldridge Dogs
{1249}{}{Rattray}                                           # RCRatray.int    ; Rattray, Doc Johnson's assistant
{1250}{}{Spouse}                                            # HCHusWif.int    ; Mutant Husband/Wife Broken Hills
{1251}{}{LoPan Guard}                                       # FCLoGrd.int     ; Lo Pan Guard
{1252}{}{Map Script}                                        # Navarro.int     ; Map script for Navarro
{1253}{}{Door}                                              # VIVltDr3.int    ; Vault Door in Vault 8 - Martin
{1254}{}{Cybernetic Dog}                                    # CcFak9.int      ; Fake K-9 Scenery obj
{1255}{}{Luke}                                              # FCNLuke.int     ; Brother Hood Rep in NCR
{1256}{}{Joshua}                                            # FCDJosh.int     ; Joshua BOS in DEN
{1257}{}{Gate}                                              # iiLockDr.int    ; Gates in Raiders area
{1258}{}{Matt}                                              # FCFMatt.int     ; Matt BOS in San Fran
{1259}{}{Door}                                              # FSBroDor.int    ; Brother Hood Door
{1260}{}{Guard}                                             # hcGrd2.int      ; Bank Guard 2 in Broken Hills
{1261}{}{Door}                                              # QIGeckDr.int    ; Door Requiring the player to use the geck
{1262}{}{Computer}                                          # FSFAce.int      ; Ace Computer system in San Fran
{1263}{}{Terminal}                                          # QITurTrm.int    ; Generic Enclave Turret Terminal
{1264}{}{Turret}                                            # QCTurret.int    ; Enclave Turrets
{1265}{}{Chuck Stodgers}                                    # hcChuck.int     ; Chuck Stodgers, Broken Hills
{1266}{}{}                                                  # htChuck.int     ; Spatial Script for waking up Chuck
{1267}{}{Terminal}                                          # viTerm.int      ; Vault City Vault Terminal
{1268}{}{Gang Thug}                                         # RCMotGng.int    ; Frog Morton's gang
{1269}{}{Cheater}                                           # ccCheat.int     ; Cheat character in Navarro
{1270}{}{}                                                  # FSTnkrDr.int    ; Tanker Doors in San Fran
{1271}{}{Peasant}                                           # SCPeaon.int     ; NCR Peaons
{1272}{}{The Lavender Flower}                               # diRebBok.int    ; Den Becky's Book
{1273}{}{Radscorpion}                                       # hcScorp.int     ; Broken Hills Scorpion
{1274}{}{Professor}                                         # hcProf.int      ; Broken Hills Professor
{1275}{}{Box}                                               # hiPrfBx1.int    ; Professor's Box in Broken Hills
{1276}{}{Box}                                               # hiPrfBx2.int    ; Professor's Box in Broken Hills
{1277}{}{Seymour}                                           # hcSeymor.int    ; Seymour the talking Plant/Broken Hills
{1278}{}{John Sullivan}                                     # hcSulvan.int    ; John Sullivan - Broken Hills
{1279}{}{Lumpy}                                             # hcLumpy.int     ; Lumpy the car accident victim - Broken Hills
{1280}{}{}                                                  # BISpyHol.int    ; Vault 15 Spy Holodisk
{1281}{}{}                                                  # SIHisHol.int    ; NCR History Holodisk
{1282}{}{}                                                  # SIWesHol.int    ; Westin Holodisk
{1283}{}{Guard}                                             # SCBGrd.int      ; Buster's Guards in NCR Entrance
{1284}{}{}                                                  # SIElnObj.int    ; Elise Notify Object
{1285}{}{}                                                  # SIGcaObj.int    ; Guard Captain Check Obj
{1286}{}{Typhon}                                            # hcTyphon.int    ; Typhon, Son of Set - Broken Hills
{1287}{}{Bodyguard}                                         # ECBdyGrd.int    ; Random Scripted Encounter with the bodyguard
{1288}{}{Map Script}                                        # Gammovie.int    ; Map Script
{1289}{}{Locker}                                            # ziLocker.int    ; Generic Locker Script
{1290}{}{Well}                                              # hiWell.int      ; Broken Hills Well
{1291}{}{Micky}                                             # hcMicky.int     ; Mickey the Dwarf - Broken Hills
{1292}{}{Turret}                                            # WCTurret.int    ; Turret for Sierra Depot
{1293}{}{Old Ghoul}                                         # hcOldGhl.int    ; Ghouls in Old-Folks Home - Broken Hills
{1294}{}{Henchman}                                          # hcHench.int     ; Broken Hills Outfitter Henchmen
{1295}{}{Elmo}                                              # hcElmo.int      ; Elmo - Broken Hills
{1296}{}{Toilet}                                            # niToilet.int    ; Toilet - Contains Grenades - New Reno
{1297}{}{Cross}                                             # niCross.int     ; Cross - Golgotha - Buried Cash
{1298}{}{Plow}                                              # viPlow1.int     ; Plow - Vault City
{1299}{}{Plow}                                              # viPlow2.int     ; Plow - Vault City
{1300}{}{Scorpion}                                          # kcScorpa.int    ; Attacking scorpion in klamath
{1301}{}{Generator}                                         # kcGnratr.int    ; Generator player needs to repair
{1302}{}{Door}                                              # kcLvatr.int     ; Elevator door in toxic caves
{1303}{}{Door}                                              # SIVDor.int      ; Vortis Slave Door
{1304}{}{Medical Pip Boy}                                   # niMedica.int    ; New Reno "Doctor Skill" Upgrade
{1305}{}{Locker}                                            # niPrstLk.int    ; New Reno Prostitute"Locker"
{1306}{}{Locker}                                            # niBigJLk.int    ; New Reno Big Jesus "Locker"
{1307}{}{Locker}                                            # niMor1Lk.int    ; New Reno Mordino No Lock/No Ignore "Locker"
{1308}{}{Locker}                                            # niBoxrLk.int    ; New Reno Boxer "Locker"
{1309}{}{Locker}                                            # niBis1Lk.int    ; New Reno Bishop Family OK "Locker"
{1310}{}{Locker}                                            # niPornLk.int    ; New Reno Porn Actress "Locker"
{1311}{}{Locker}                                            # niBtchLk.int    ; New Reno Bitch "Locker"
{1312}{}{Locker}                                            # niBis2Lk.int    ; New Reno Bishop Family NO IGNORE "Locker"
{1313}{}{Locker}                                            # niEldrLk.int    ; New Reno Eldridge "Locker"
{1314}{}{Locker}                                            # niWrT1Lk.int    ; New Reno Wright Teen NO IGNORE "Locker"
{1315}{}{Locker}                                            # niOWriLk.int    ; New Reno Orville Wright "Locker"
{1316}{}{Locker}                                            # niWrT2Lk.int    ; New Reno Wright Teen FAMILY IGNORE "Locker"
{1317}{}{Locker}                                            # niMor1Lk.int    ; New Reno Mordino FAMILY IGNORE "Locker"
{1318}{}{Locker}                                            # niMyGdLk.int    ; New Reno Myron Guard "Locker"
{1319}{}{Locker}                                            # niMor2Lk.int    ; New Reno Mordino NO IGNORE "Locker"
{1320}{}{Locker}                                            # niMyrnLk.int    ; New Reno Myron "Locker"
{1321}{}{Locker}                                            # niChp1Lk.int    ; New Reno Chop Shop Boy LOCKED "Locker"
{1322}{}{Locker}                                            # niChp2Lk.int    ; New Reno Chop Shop Boy NO-LOCK "Locker"
{1323}{}{Locker}                                            # niTryLk.int     ; New Reno Tray "Locker"
{1324}{}{Locker}                                            # niMor3Lk.int    ; New Reno Mordino locker, no warning
{1325}{}{Map Script}                                        # rndToxic.int    ; Map Script
{1326}{}{You can't see me}                                  # ECirrad.int     ; Critter is hidden and irradiates.
{1327}{}{Tin Woodsman}                                      # ECTinWod.int    ; Tin Woodsman
{1328}{}{Map Script}                                        # RNDTinWd.int    ; Tin Woodsman Map Script
{1329}{}{Stone Formation}                                   # ecGrdFrv.int    ; Guardian of Forever
{1330}{}{}                                                  # rndForvr.int    ; Guardian of Forever Rnd Enct Map Script
{1331}{}{Terminal}                                          # ecGrdTrm.int    ; Guardian of Forever Water Chip terminal
{1332}{}{Locker}                                            # niEld2Lk.int    ; New Reno Eldridge "Locker" HARD LOCK
{1333}{}{}                                                  # SIRagobj.int    ; Uhh box that rondo cares about it.
{1334}{}{Map Script}                                        # sfchina2.int    ; China 2 Map Script
{1335}{}{Security Bot}                                      # WCDedBot.int    ; Fighting Bot that does nothing
{1336}{}{Security Bot}                                      # KCWupass.int    ; Klamath Guard Robot under Toxic Caves
{1337}{}{Locker}                                            # viHarWch.int    ; VCty - Harry Watch Script
{1338}{}{Locker}                                            # viEdWch.int     ; VCty - Ed Watch Script
{1339}{}{Locker}                                            # viAndWch.int    ; VCty - Doc Andrew Watch Script
{1340}{}{Locker}                                            # viLynWch.int    ; VCty - Lynette Watch Script
{1341}{}{Locker}                                            # viGrgWch.int    ; VCty - Gregory Watch Script
{1342}{}{Locker}                                            # viCGWch1.int    ; VCty - Prison Door Watch Script
{1343}{}{Locker}                                            # viCGWch2.int    ; VCty - Greeting Watch Script
{1344}{}{Locker}                                            # viRNWch1.int    ; VCty - Randal1 Watch Script
{1345}{}{Locker}                                            # viRNWch2.int    ; VCty - Randal2 Watch Script
{1346}{}{Locker}                                            # viStkWch.int    ; VCty - Stark Watch Script
{1347}{}{Locker}                                            # viBarWch.int    ; VCty - Barkus Watch Script
{1348}{}{Locker}                                            # viVLWch1.int    ; VCty - Valerie1 Watch Script
{1349}{}{Locker}                                            # viVLWch2.int    ; VCty - Valerie2 Watch Script
{1350}{}{Locker}                                            # viWalWch.int    ; VCty - Wallace Watch Script
{1351}{}{Locker}                                            # viSkvWch.int    ; VCty - Greeting Watch Script
{1352}{}{Locker}                                            # viInWch1.int    ; VCty - InGrd Watch Script
{1353}{}{Locker}                                            # viInWch2.int    ; VCty - InGrd Watch Script
{1354}{}{Locker}                                            # viInWch3.int    ; VCty - InGrd Watch Script
{1355}{}{Locker}                                            # viFamWch.int    ; VCty - GenFam Watch Script
{1356}{}{Locker}                                            # viCsWch1.int    ; VCty - Cassidy Watch Script
{1357}{}{Dock Squatter}                                     # FCDocSqa.int    ; San Fran Doc Squatters
{1358}{}{Dock Kid}                                          # FCDocKid.int    ; San Fran Doc Kids
{1359}{}{Map Script}                                        # RndWhale.int    ; Random Whale Map
{1360}{}{Percy Crump}                                       # gcPercy.int     ; Percy Crump, Merchant in Gecko
{1361}{}{Box}                                               # giPerBox.int    ; Percy's Stock Box
{1362}{}{Box}                                               # giJnkBox.int    ; Gecko Junkyard Temp Inventory Box
{1363}{}{Door}                                              # niWriDor.int    ; New Reno Wright Room Door
{1364}{}{The Great Ananias}                                 # dcAnan.int      ; The Great Ananias, Mummy Master
{1365}{}{Map Script}                                        # rndUvilg.int    ; Map Script Unwashed
{1366}{}{Unwashed Villager}                                 # ecwash.int      ; Villagers on the above map
{1367}{}{Spammer}                                           # ecspammr.int    ; Spammer in Unwashed
{1368}{}{Map}                                               # eiSanMap.int    ; Military Base San Francisco Map
{1369}{}{Map Script}                                        # rndShutl.int    ; Random Shuttle encounter map
{1370}{}{Map Script}                                        # rndParih.int    ; Random Pariah Map Script
{1371}{}{Map Script}                                        # rndBHead.int    ; Random Big Head map
{1372}{}{Map Script}                                        # rndcafe.int     ; Random Cafe Map
{1373}{}{Nuka-Cola Machine}                                 # zinuke.int      ; Nuka Cola Machine
{1374}{}{Dock}                                              # sfdock.int      ; map script for San Fran Dock
{1375}{}{Door}                                              # ciCrisDr.int    ; Chris's Door
{1376}{}{Land Mine}                                         # rtlndmin.int    ; Redding Land Mines
{1377}{}{Land Mine}                                         # wtlndmin.int    ; Sierra Depot Land Mines
{1378}{}{Your Ex}                                           # ncExSpou.int    ; New Reno Ex-Spouse script
{1379}{}{Mel}                                               # ecMel.int       ; Mel That dog meat creates
{1380}{}{Vent}                                              # ciVent.int      ; Vent into Navarro
{1381}{}{Kevin}                                             # ccKevin.int     ; Kevin in Navarro
{1382}{}{Alarm}                                             # csAlarm.int     ; Navarro base on alert lights
{1383}{}{Locker}                                            # ciQunWch.int    ; Quincy Locker Watch Script
{1384}{}{Locker}                                            # ciRulWch.int    ; Raul Locker Watch Script
{1385}{}{Locker}                                            # ciCmdWch.int    ; Commanded Locker Watch Script
{1386}{}{}                                                  # SSStat.int      ; NCR Statue
{1387}{}{}                                                  # ctFob.int       ; Fob EXP Spatial Script
{1388}{}{}                                                  # ctPlans.int     ; Vertibird EXP Spatial Script
{1389}{}{}                                                  # ctK9Part.int    ; K9 Part EXP Spatial Script
{1390}{}{}                                                  # csArea2.int     ; Script to signal if dude enters an area
{1391}{}{}                                                  # csOpen2.int     ; Script to signal if dude uses door w/o permis
{1392}{}{}                                                  # ctSound.int     ; Soundproof Room Spatial Script
{1393}{}{}                                                  # csOpen3.int     ; Script to signal if dude uses door w/o permis
{1394}{}{Bootlegger}                                        # ECTlkMon.int    ; Talking Moonshiners
{1395}{}{}                                                  # ziWeakLk.int    ; Generic Weak Lock Watch Script
{1396}{}{}                                                  # ziMedmLk.int    ; Generic Medium Lock Watch Script
{1397}{}{Carny Kid}                                         # dcCarnKd.int    ; Carny Kid - The Den
{1398}{}{}                                                  # ciDocWch.int    ; Raul Locker Watch Script
{1399}{}{}                                                  # ziHardLk.int    ; Generic Hard Lock Watch Script
{1400}{}{Mine}                                              # CIMine.int      ; Mines in Navarro
{1401}{}{Locker}                                            # niBisHLk.int    ; New Reno Bishop Hard Locker
{1402}{}{Door}                                              # niBisHDr.int    ; New Reno Bishop Hard Locked Door
{1403}{}{}                                                  # ntRicRom.int    ; New Reno Richard Wright Room Spacial
{1404}{}{}                                                  # FLUFFY.int      ; 
